/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Asignatura implements Serializable
{
	/** 
	 * This attribute maps to the column ASIGNATURA_ID in the ASIGNATURA table.
	 */
	protected long asignaturaId;

	/** 
	 * This attribute maps to the column NOMBRE in the ASIGNATURA table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column CREDITOS in the ASIGNATURA table.
	 */
	protected int creditos;

	/** 
	 * This attribute maps to the column ASIGNATURA_REQUERIDA_ID in the ASIGNATURA table.
	 */
	protected long asignaturaRequeridaId;

	/** 
	 * This attribute represents whether the primitive attribute asignaturaRequeridaId is null.
	 */
	protected boolean asignaturaRequeridaIdNull = true;

	/** 
	 * This attribute maps to the column PLAN_ESTUDIOS_ID in the ASIGNATURA table.
	 */
	protected int planEstudiosId;

	/**
	 * Method 'Asignatura'
	 * 
	 */
	public Asignatura()
	{
	}

	/**
	 * Method 'getAsignaturaId'
	 * 
	 * @return long
	 */
	public long getAsignaturaId()
	{
		return asignaturaId;
	}

	/**
	 * Method 'setAsignaturaId'
	 * 
	 * @param asignaturaId
	 */
	public void setAsignaturaId(long asignaturaId)
	{
		this.asignaturaId = asignaturaId;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getCreditos'
	 * 
	 * @return int
	 */
	public int getCreditos()
	{
		return creditos;
	}

	/**
	 * Method 'setCreditos'
	 * 
	 * @param creditos
	 */
	public void setCreditos(int creditos)
	{
		this.creditos = creditos;
	}

	/**
	 * Method 'getAsignaturaRequeridaId'
	 * 
	 * @return long
	 */
	public long getAsignaturaRequeridaId()
	{
		return asignaturaRequeridaId;
	}

	/**
	 * Method 'setAsignaturaRequeridaId'
	 * 
	 * @param asignaturaRequeridaId
	 */
	public void setAsignaturaRequeridaId(long asignaturaRequeridaId)
	{
		this.asignaturaRequeridaId = asignaturaRequeridaId;
		this.asignaturaRequeridaIdNull = false;
	}

	/**
	 * Method 'setAsignaturaRequeridaIdNull'
	 * 
	 * @param value
	 */
	public void setAsignaturaRequeridaIdNull(boolean value)
	{
		this.asignaturaRequeridaIdNull = value;
	}

	/**
	 * Method 'isAsignaturaRequeridaIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isAsignaturaRequeridaIdNull()
	{
		return asignaturaRequeridaIdNull;
	}

	/**
	 * Method 'getPlanEstudiosId'
	 * 
	 * @return int
	 */
	public int getPlanEstudiosId()
	{
		return planEstudiosId;
	}

	/**
	 * Method 'setPlanEstudiosId'
	 * 
	 * @param planEstudiosId
	 */
	public void setPlanEstudiosId(int planEstudiosId)
	{
		this.planEstudiosId = planEstudiosId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Asignatura)) {
			return false;
		}
		
		final Asignatura _cast = (Asignatura) _other;
		if (asignaturaId != _cast.asignaturaId) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (creditos != _cast.creditos) {
			return false;
		}
		
		if (asignaturaRequeridaId != _cast.asignaturaRequeridaId) {
			return false;
		}
		
		if (asignaturaRequeridaIdNull != _cast.asignaturaRequeridaIdNull) {
			return false;
		}
		
		if (planEstudiosId != _cast.planEstudiosId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (asignaturaId ^ (asignaturaId >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + creditos;
		_hashCode = 29 * _hashCode + (int) (asignaturaRequeridaId ^ (asignaturaRequeridaId >>> 32));
		_hashCode = 29 * _hashCode + (asignaturaRequeridaIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + planEstudiosId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AsignaturaPk
	 */
	public AsignaturaPk createPk()
	{
		return new AsignaturaPk(asignaturaId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.Asignatura: " );
		ret.append( "asignaturaId=" + asignaturaId );
		ret.append( ", nombre=" + nombre );
		ret.append( ", creditos=" + creditos );
		ret.append( ", asignaturaRequeridaId=" + asignaturaRequeridaId );
		ret.append( ", planEstudiosId=" + planEstudiosId );
		return ret.toString();
	}

}
