/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ASIGNATURA table.
 */
public class AsignaturaPk implements Serializable
{
	protected long asignaturaId;

	/** 
	 * This attribute represents whether the primitive attribute asignaturaId is null.
	 */
	protected boolean asignaturaIdNull;

	/** 
	 * Sets the value of asignaturaId
	 */
	public void setAsignaturaId(long asignaturaId)
	{
		this.asignaturaId = asignaturaId;
	}

	/** 
	 * Gets the value of asignaturaId
	 */
	public long getAsignaturaId()
	{
		return asignaturaId;
	}

	/**
	 * Method 'AsignaturaPk'
	 * 
	 */
	public AsignaturaPk()
	{
	}

	/**
	 * Method 'AsignaturaPk'
	 * 
	 * @param asignaturaId
	 */
	public AsignaturaPk(final long asignaturaId)
	{
		this.asignaturaId = asignaturaId;
	}

	/** 
	 * Sets the value of asignaturaIdNull
	 */
	public void setAsignaturaIdNull(boolean asignaturaIdNull)
	{
		this.asignaturaIdNull = asignaturaIdNull;
	}

	/** 
	 * Gets the value of asignaturaIdNull
	 */
	public boolean isAsignaturaIdNull()
	{
		return asignaturaIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AsignaturaPk)) {
			return false;
		}
		
		final AsignaturaPk _cast = (AsignaturaPk) _other;
		if (asignaturaId != _cast.asignaturaId) {
			return false;
		}
		
		if (asignaturaIdNull != _cast.asignaturaIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (asignaturaId ^ (asignaturaId >>> 32));
		_hashCode = 29 * _hashCode + (asignaturaIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.AsignaturaPk: " );
		ret.append( "asignaturaId=" + asignaturaId );
		return ret.toString();
	}

}
