/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Curso implements Serializable
{
	/** 
	 * This attribute maps to the column CURSO_ID in the CURSO table.
	 */
	protected long cursoId;

	/** 
	 * This attribute maps to the column CUPO_MAXIMO in the CURSO table.
	 */
	protected int cupoMaximo;

	/** 
	 * This attribute maps to the column PROFESOR_ID in the CURSO table.
	 */
	protected long profesorId;

	/** 
	 * This attribute maps to the column ASIGNATURA_ID in the CURSO table.
	 */
	protected long asignaturaId;

	/** 
	 * This attribute maps to the column SEMESTRE_ID in the CURSO table.
	 */
	protected long semestreId;

	/** 
	 * This attribute maps to the column CLAVE_GRUPO in the CURSO table.
	 */
	protected String claveGrupo;

	/**
	 * Method 'Curso'
	 * 
	 */
	public Curso()
	{
	}

	/**
	 * Method 'getCursoId'
	 * 
	 * @return long
	 */
	public long getCursoId()
	{
		return cursoId;
	}

	/**
	 * Method 'setCursoId'
	 * 
	 * @param cursoId
	 */
	public void setCursoId(long cursoId)
	{
		this.cursoId = cursoId;
	}

	/**
	 * Method 'getCupoMaximo'
	 * 
	 * @return int
	 */
	public int getCupoMaximo()
	{
		return cupoMaximo;
	}

	/**
	 * Method 'setCupoMaximo'
	 * 
	 * @param cupoMaximo
	 */
	public void setCupoMaximo(int cupoMaximo)
	{
		this.cupoMaximo = cupoMaximo;
	}

	/**
	 * Method 'getProfesorId'
	 * 
	 * @return long
	 */
	public long getProfesorId()
	{
		return profesorId;
	}

	/**
	 * Method 'setProfesorId'
	 * 
	 * @param profesorId
	 */
	public void setProfesorId(long profesorId)
	{
		this.profesorId = profesorId;
	}

	/**
	 * Method 'getAsignaturaId'
	 * 
	 * @return long
	 */
	public long getAsignaturaId()
	{
		return asignaturaId;
	}

	/**
	 * Method 'setAsignaturaId'
	 * 
	 * @param asignaturaId
	 */
	public void setAsignaturaId(long asignaturaId)
	{
		this.asignaturaId = asignaturaId;
	}

	/**
	 * Method 'getSemestreId'
	 * 
	 * @return long
	 */
	public long getSemestreId()
	{
		return semestreId;
	}

	/**
	 * Method 'setSemestreId'
	 * 
	 * @param semestreId
	 */
	public void setSemestreId(long semestreId)
	{
		this.semestreId = semestreId;
	}

	/**
	 * Method 'getClaveGrupo'
	 * 
	 * @return String
	 */
	public String getClaveGrupo()
	{
		return claveGrupo;
	}

	/**
	 * Method 'setClaveGrupo'
	 * 
	 * @param claveGrupo
	 */
	public void setClaveGrupo(String claveGrupo)
	{
		this.claveGrupo = claveGrupo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Curso)) {
			return false;
		}
		
		final Curso _cast = (Curso) _other;
		if (cursoId != _cast.cursoId) {
			return false;
		}
		
		if (cupoMaximo != _cast.cupoMaximo) {
			return false;
		}
		
		if (profesorId != _cast.profesorId) {
			return false;
		}
		
		if (asignaturaId != _cast.asignaturaId) {
			return false;
		}
		
		if (semestreId != _cast.semestreId) {
			return false;
		}
		
		if (claveGrupo == null ? _cast.claveGrupo != claveGrupo : !claveGrupo.equals( _cast.claveGrupo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (cursoId ^ (cursoId >>> 32));
		_hashCode = 29 * _hashCode + cupoMaximo;
		_hashCode = 29 * _hashCode + (int) (profesorId ^ (profesorId >>> 32));
		_hashCode = 29 * _hashCode + (int) (asignaturaId ^ (asignaturaId >>> 32));
		_hashCode = 29 * _hashCode + (int) (semestreId ^ (semestreId >>> 32));
		if (claveGrupo != null) {
			_hashCode = 29 * _hashCode + claveGrupo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CursoPk
	 */
	public CursoPk createPk()
	{
		return new CursoPk(cursoId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.Curso: " );
		ret.append( "cursoId=" + cursoId );
		ret.append( ", cupoMaximo=" + cupoMaximo );
		ret.append( ", profesorId=" + profesorId );
		ret.append( ", asignaturaId=" + asignaturaId );
		ret.append( ", semestreId=" + semestreId );
		ret.append( ", claveGrupo=" + claveGrupo );
		return ret.toString();
	}

}
