/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CURSO_HORARIO table.
 */
public class CursoHorarioPk implements Serializable
{
	protected long cursoHorarioId;

	/** 
	 * This attribute represents whether the primitive attribute cursoHorarioId is null.
	 */
	protected boolean cursoHorarioIdNull;

	/** 
	 * Sets the value of cursoHorarioId
	 */
	public void setCursoHorarioId(long cursoHorarioId)
	{
		this.cursoHorarioId = cursoHorarioId;
	}

	/** 
	 * Gets the value of cursoHorarioId
	 */
	public long getCursoHorarioId()
	{
		return cursoHorarioId;
	}

	/**
	 * Method 'CursoHorarioPk'
	 * 
	 */
	public CursoHorarioPk()
	{
	}

	/**
	 * Method 'CursoHorarioPk'
	 * 
	 * @param cursoHorarioId
	 */
	public CursoHorarioPk(final long cursoHorarioId)
	{
		this.cursoHorarioId = cursoHorarioId;
	}

	/** 
	 * Sets the value of cursoHorarioIdNull
	 */
	public void setCursoHorarioIdNull(boolean cursoHorarioIdNull)
	{
		this.cursoHorarioIdNull = cursoHorarioIdNull;
	}

	/** 
	 * Gets the value of cursoHorarioIdNull
	 */
	public boolean isCursoHorarioIdNull()
	{
		return cursoHorarioIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CursoHorarioPk)) {
			return false;
		}
		
		final CursoHorarioPk _cast = (CursoHorarioPk) _other;
		if (cursoHorarioId != _cast.cursoHorarioId) {
			return false;
		}
		
		if (cursoHorarioIdNull != _cast.cursoHorarioIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (cursoHorarioId ^ (cursoHorarioId >>> 32));
		_hashCode = 29 * _hashCode + (cursoHorarioIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.CursoHorarioPk: " );
		ret.append( "cursoHorarioId=" + cursoHorarioId );
		return ret.toString();
	}

}
