/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CursoHorario implements Serializable
{
	/** 
	 * This attribute maps to the column CURSO_HORARIO_ID in the CURSO_HORARIO table.
	 */
	protected long cursoHorarioId;

	/** 
	 * This attribute maps to the column CURSO_ID in the CURSO_HORARIO table.
	 */
	protected long cursoId;

	/** 
	 * This attribute maps to the column HORARIO_ID in the CURSO_HORARIO table.
	 */
	protected long horarioId;

	/**
	 * Method 'CursoHorario'
	 * 
	 */
	public CursoHorario()
	{
	}

	/**
	 * Method 'getCursoHorarioId'
	 * 
	 * @return long
	 */
	public long getCursoHorarioId()
	{
		return cursoHorarioId;
	}

	/**
	 * Method 'setCursoHorarioId'
	 * 
	 * @param cursoHorarioId
	 */
	public void setCursoHorarioId(long cursoHorarioId)
	{
		this.cursoHorarioId = cursoHorarioId;
	}

	/**
	 * Method 'getCursoId'
	 * 
	 * @return long
	 */
	public long getCursoId()
	{
		return cursoId;
	}

	/**
	 * Method 'setCursoId'
	 * 
	 * @param cursoId
	 */
	public void setCursoId(long cursoId)
	{
		this.cursoId = cursoId;
	}

	/**
	 * Method 'getHorarioId'
	 * 
	 * @return long
	 */
	public long getHorarioId()
	{
		return horarioId;
	}

	/**
	 * Method 'setHorarioId'
	 * 
	 * @param horarioId
	 */
	public void setHorarioId(long horarioId)
	{
		this.horarioId = horarioId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CursoHorario)) {
			return false;
		}
		
		final CursoHorario _cast = (CursoHorario) _other;
		if (cursoHorarioId != _cast.cursoHorarioId) {
			return false;
		}
		
		if (cursoId != _cast.cursoId) {
			return false;
		}
		
		if (horarioId != _cast.horarioId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (cursoHorarioId ^ (cursoHorarioId >>> 32));
		_hashCode = 29 * _hashCode + (int) (cursoId ^ (cursoId >>> 32));
		_hashCode = 29 * _hashCode + (int) (horarioId ^ (horarioId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CursoHorarioPk
	 */
	public CursoHorarioPk createPk()
	{
		return new CursoHorarioPk(cursoHorarioId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.CursoHorario: " );
		ret.append( "cursoHorarioId=" + cursoHorarioId );
		ret.append( ", cursoId=" + cursoId );
		ret.append( ", horarioId=" + horarioId );
		return ret.toString();
	}

}
