/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CURSO table.
 */
public class CursoPk implements Serializable
{
	protected long cursoId;

	/** 
	 * This attribute represents whether the primitive attribute cursoId is null.
	 */
	protected boolean cursoIdNull;

	/** 
	 * Sets the value of cursoId
	 */
	public void setCursoId(long cursoId)
	{
		this.cursoId = cursoId;
	}

	/** 
	 * Gets the value of cursoId
	 */
	public long getCursoId()
	{
		return cursoId;
	}

	/**
	 * Method 'CursoPk'
	 * 
	 */
	public CursoPk()
	{
	}

	/**
	 * Method 'CursoPk'
	 * 
	 * @param cursoId
	 */
	public CursoPk(final long cursoId)
	{
		this.cursoId = cursoId;
	}

	/** 
	 * Sets the value of cursoIdNull
	 */
	public void setCursoIdNull(boolean cursoIdNull)
	{
		this.cursoIdNull = cursoIdNull;
	}

	/** 
	 * Gets the value of cursoIdNull
	 */
	public boolean isCursoIdNull()
	{
		return cursoIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CursoPk)) {
			return false;
		}
		
		final CursoPk _cast = (CursoPk) _other;
		if (cursoId != _cast.cursoId) {
			return false;
		}
		
		if (cursoIdNull != _cast.cursoIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (cursoId ^ (cursoId >>> 32));
		_hashCode = 29 * _hashCode + (cursoIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.CursoPk: " );
		ret.append( "cursoId=" + cursoId );
		return ret.toString();
	}

}
