/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Estudiante implements Serializable
{
	/** 
	 * This attribute maps to the column ESTUDIANTE_ID in the ESTUDIANTE table.
	 */
	protected long estudianteId;

	/** 
	 * This attribute maps to the column NOMBRE in the ESTUDIANTE table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column APELLIDO_PATERNO in the ESTUDIANTE table.
	 */
	protected String apellidoPaterno;

	/** 
	 * This attribute maps to the column APELLIDO_MATERNO in the ESTUDIANTE table.
	 */
	protected String apellidoMaterno;

	/** 
	 * This attribute maps to the column FECHA_NACIMIENTO in the ESTUDIANTE table.
	 */
	protected Date fechaNacimiento;

	/** 
	 * This attribute maps to the column FOTOGRAFIA in the ESTUDIANTE table.
	 */
	protected byte[] fotografia;

	/** 
	 * This attribute maps to the column PLAN_ESTUDIOS_ID in the ESTUDIANTE table.
	 */
	protected int planEstudiosId;

	/** 
	 * This attribute represents whether the primitive attribute planEstudiosId is null.
	 */
	protected boolean planEstudiosIdNull = true;

	/**
	 * Method 'Estudiante'
	 * 
	 */
	public Estudiante()
	{
	}

	/**
	 * Method 'getEstudianteId'
	 * 
	 * @return long
	 */
	public long getEstudianteId()
	{
		return estudianteId;
	}

	/**
	 * Method 'setEstudianteId'
	 * 
	 * @param estudianteId
	 */
	public void setEstudianteId(long estudianteId)
	{
		this.estudianteId = estudianteId;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getApellidoPaterno'
	 * 
	 * @return String
	 */
	public String getApellidoPaterno()
	{
		return apellidoPaterno;
	}

	/**
	 * Method 'setApellidoPaterno'
	 * 
	 * @param apellidoPaterno
	 */
	public void setApellidoPaterno(String apellidoPaterno)
	{
		this.apellidoPaterno = apellidoPaterno;
	}

	/**
	 * Method 'getApellidoMaterno'
	 * 
	 * @return String
	 */
	public String getApellidoMaterno()
	{
		return apellidoMaterno;
	}

	/**
	 * Method 'setApellidoMaterno'
	 * 
	 * @param apellidoMaterno
	 */
	public void setApellidoMaterno(String apellidoMaterno)
	{
		this.apellidoMaterno = apellidoMaterno;
	}

	/**
	 * Method 'getFechaNacimiento'
	 * 
	 * @return Date
	 */
	public Date getFechaNacimiento()
	{
		return fechaNacimiento;
	}

	/**
	 * Method 'setFechaNacimiento'
	 * 
	 * @param fechaNacimiento
	 */
	public void setFechaNacimiento(Date fechaNacimiento)
	{
		this.fechaNacimiento = fechaNacimiento;
	}

	/**
	 * Method 'getFotografia'
	 * 
	 * @return byte[]
	 */
	public byte[] getFotografia()
	{
		return fotografia;
	}

	/**
	 * Method 'setFotografia'
	 * 
	 * @param fotografia
	 */
	public void setFotografia(byte[] fotografia)
	{
		this.fotografia = fotografia;
	}

	/**
	 * Method 'getPlanEstudiosId'
	 * 
	 * @return int
	 */
	public int getPlanEstudiosId()
	{
		return planEstudiosId;
	}

	/**
	 * Method 'setPlanEstudiosId'
	 * 
	 * @param planEstudiosId
	 */
	public void setPlanEstudiosId(int planEstudiosId)
	{
		this.planEstudiosId = planEstudiosId;
		this.planEstudiosIdNull = false;
	}

	/**
	 * Method 'setPlanEstudiosIdNull'
	 * 
	 * @param value
	 */
	public void setPlanEstudiosIdNull(boolean value)
	{
		this.planEstudiosIdNull = value;
	}

	/**
	 * Method 'isPlanEstudiosIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isPlanEstudiosIdNull()
	{
		return planEstudiosIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Estudiante)) {
			return false;
		}
		
		final Estudiante _cast = (Estudiante) _other;
		if (estudianteId != _cast.estudianteId) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (apellidoPaterno == null ? _cast.apellidoPaterno != apellidoPaterno : !apellidoPaterno.equals( _cast.apellidoPaterno )) {
			return false;
		}
		
		if (apellidoMaterno == null ? _cast.apellidoMaterno != apellidoMaterno : !apellidoMaterno.equals( _cast.apellidoMaterno )) {
			return false;
		}
		
		if (fechaNacimiento == null ? _cast.fechaNacimiento != fechaNacimiento : !fechaNacimiento.equals( _cast.fechaNacimiento )) {
			return false;
		}
		
		if (fotografia == null ? _cast.fotografia != fotografia : !fotografia.equals( _cast.fotografia )) {
			return false;
		}
		
		if (planEstudiosId != _cast.planEstudiosId) {
			return false;
		}
		
		if (planEstudiosIdNull != _cast.planEstudiosIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (estudianteId ^ (estudianteId >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (apellidoPaterno != null) {
			_hashCode = 29 * _hashCode + apellidoPaterno.hashCode();
		}
		
		if (apellidoMaterno != null) {
			_hashCode = 29 * _hashCode + apellidoMaterno.hashCode();
		}
		
		if (fechaNacimiento != null) {
			_hashCode = 29 * _hashCode + fechaNacimiento.hashCode();
		}
		
		if (fotografia != null) {
			_hashCode = 29 * _hashCode + fotografia.hashCode();
		}
		
		_hashCode = 29 * _hashCode + planEstudiosId;
		_hashCode = 29 * _hashCode + (planEstudiosIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EstudiantePk
	 */
	public EstudiantePk createPk()
	{
		return new EstudiantePk(estudianteId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.Estudiante: " );
		ret.append( "estudianteId=" + estudianteId );
		ret.append( ", nombre=" + nombre );
		ret.append( ", apellidoPaterno=" + apellidoPaterno );
		ret.append( ", apellidoMaterno=" + apellidoMaterno );
		ret.append( ", fechaNacimiento=" + fechaNacimiento );
		ret.append( ", fotografia=" + fotografia );
		ret.append( ", planEstudiosId=" + planEstudiosId );
		return ret.toString();
	}

}
