/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ESTUDIANTE table.
 */
public class EstudiantePk implements Serializable
{
	protected long estudianteId;

	/** 
	 * This attribute represents whether the primitive attribute estudianteId is null.
	 */
	protected boolean estudianteIdNull;

	/** 
	 * Sets the value of estudianteId
	 */
	public void setEstudianteId(long estudianteId)
	{
		this.estudianteId = estudianteId;
	}

	/** 
	 * Gets the value of estudianteId
	 */
	public long getEstudianteId()
	{
		return estudianteId;
	}

	/**
	 * Method 'EstudiantePk'
	 * 
	 */
	public EstudiantePk()
	{
	}

	/**
	 * Method 'EstudiantePk'
	 * 
	 * @param estudianteId
	 */
	public EstudiantePk(final long estudianteId)
	{
		this.estudianteId = estudianteId;
	}

	/** 
	 * Sets the value of estudianteIdNull
	 */
	public void setEstudianteIdNull(boolean estudianteIdNull)
	{
		this.estudianteIdNull = estudianteIdNull;
	}

	/** 
	 * Gets the value of estudianteIdNull
	 */
	public boolean isEstudianteIdNull()
	{
		return estudianteIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstudiantePk)) {
			return false;
		}
		
		final EstudiantePk _cast = (EstudiantePk) _other;
		if (estudianteId != _cast.estudianteId) {
			return false;
		}
		
		if (estudianteIdNull != _cast.estudianteIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (estudianteId ^ (estudianteId >>> 32));
		_hashCode = 29 * _hashCode + (estudianteIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.EstudiantePk: " );
		ret.append( "estudianteId=" + estudianteId );
		return ret.toString();
	}

}
