/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class EstudianteInscrito implements Serializable
{
	/** 
	 * This attribute maps to the column ESTUDIANTE_INSCRITO_ID in the ESTUDIANTE_INSCRITO table.
	 */
	protected long estudianteInscritoId;

	/** 
	 * This attribute maps to the column CURSO_ID in the ESTUDIANTE_INSCRITO table.
	 */
	protected long cursoId;

	/** 
	 * This attribute represents whether the primitive attribute cursoId is null.
	 */
	protected boolean cursoIdNull = true;

	/** 
	 * This attribute maps to the column ESTUDIANTE_ID in the ESTUDIANTE_INSCRITO table.
	 */
	protected long estudianteId;

	/** 
	 * This attribute represents whether the primitive attribute estudianteId is null.
	 */
	protected boolean estudianteIdNull = true;

	/** 
	 * This attribute maps to the column CALIFICACION in the ESTUDIANTE_INSCRITO table.
	 */
	protected int calificacion;

	/** 
	 * This attribute represents whether the primitive attribute calificacion is null.
	 */
	protected boolean calificacionNull = true;

	/**
	 * Method 'EstudianteInscrito'
	 * 
	 */
	public EstudianteInscrito()
	{
	}

	/**
	 * Method 'getEstudianteInscritoId'
	 * 
	 * @return long
	 */
	public long getEstudianteInscritoId()
	{
		return estudianteInscritoId;
	}

	/**
	 * Method 'setEstudianteInscritoId'
	 * 
	 * @param estudianteInscritoId
	 */
	public void setEstudianteInscritoId(long estudianteInscritoId)
	{
		this.estudianteInscritoId = estudianteInscritoId;
	}

	/**
	 * Method 'getCursoId'
	 * 
	 * @return long
	 */
	public long getCursoId()
	{
		return cursoId;
	}

	/**
	 * Method 'setCursoId'
	 * 
	 * @param cursoId
	 */
	public void setCursoId(long cursoId)
	{
		this.cursoId = cursoId;
		this.cursoIdNull = false;
	}

	/**
	 * Method 'setCursoIdNull'
	 * 
	 * @param value
	 */
	public void setCursoIdNull(boolean value)
	{
		this.cursoIdNull = value;
	}

	/**
	 * Method 'isCursoIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isCursoIdNull()
	{
		return cursoIdNull;
	}

	/**
	 * Method 'getEstudianteId'
	 * 
	 * @return long
	 */
	public long getEstudianteId()
	{
		return estudianteId;
	}

	/**
	 * Method 'setEstudianteId'
	 * 
	 * @param estudianteId
	 */
	public void setEstudianteId(long estudianteId)
	{
		this.estudianteId = estudianteId;
		this.estudianteIdNull = false;
	}

	/**
	 * Method 'setEstudianteIdNull'
	 * 
	 * @param value
	 */
	public void setEstudianteIdNull(boolean value)
	{
		this.estudianteIdNull = value;
	}

	/**
	 * Method 'isEstudianteIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isEstudianteIdNull()
	{
		return estudianteIdNull;
	}

	/**
	 * Method 'getCalificacion'
	 * 
	 * @return int
	 */
	public int getCalificacion()
	{
		return calificacion;
	}

	/**
	 * Method 'setCalificacion'
	 * 
	 * @param calificacion
	 */
	public void setCalificacion(int calificacion)
	{
		this.calificacion = calificacion;
		this.calificacionNull = false;
	}

	/**
	 * Method 'setCalificacionNull'
	 * 
	 * @param value
	 */
	public void setCalificacionNull(boolean value)
	{
		this.calificacionNull = value;
	}

	/**
	 * Method 'isCalificacionNull'
	 * 
	 * @return boolean
	 */
	public boolean isCalificacionNull()
	{
		return calificacionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstudianteInscrito)) {
			return false;
		}
		
		final EstudianteInscrito _cast = (EstudianteInscrito) _other;
		if (estudianteInscritoId != _cast.estudianteInscritoId) {
			return false;
		}
		
		if (cursoId != _cast.cursoId) {
			return false;
		}
		
		if (cursoIdNull != _cast.cursoIdNull) {
			return false;
		}
		
		if (estudianteId != _cast.estudianteId) {
			return false;
		}
		
		if (estudianteIdNull != _cast.estudianteIdNull) {
			return false;
		}
		
		if (calificacion != _cast.calificacion) {
			return false;
		}
		
		if (calificacionNull != _cast.calificacionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (estudianteInscritoId ^ (estudianteInscritoId >>> 32));
		_hashCode = 29 * _hashCode + (int) (cursoId ^ (cursoId >>> 32));
		_hashCode = 29 * _hashCode + (cursoIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (estudianteId ^ (estudianteId >>> 32));
		_hashCode = 29 * _hashCode + (estudianteIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + calificacion;
		_hashCode = 29 * _hashCode + (calificacionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EstudianteInscritoPk
	 */
	public EstudianteInscritoPk createPk()
	{
		return new EstudianteInscritoPk(estudianteInscritoId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.EstudianteInscrito: " );
		ret.append( "estudianteInscritoId=" + estudianteInscritoId );
		ret.append( ", cursoId=" + cursoId );
		ret.append( ", estudianteId=" + estudianteId );
		ret.append( ", calificacion=" + calificacion );
		return ret.toString();
	}

}
