/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class EstudianteExtraordinario implements Serializable
{
	/** 
	 * This attribute maps to the column ESTUDIANTE_ID in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	protected long estudianteId;

	/** 
	 * This attribute maps to the column NUM_EXAMEN in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	protected int numExamen;

	/** 
	 * This attribute maps to the column CALIFICACION in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	protected float calificacion;

	/** 
	 * This attribute maps to the column ASIGNATURA_ID in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	protected long asignaturaId;

	/**
	 * Method 'EstudianteExtraordinario'
	 * 
	 */
	public EstudianteExtraordinario()
	{
	}

	/**
	 * Method 'getEstudianteId'
	 * 
	 * @return long
	 */
	public long getEstudianteId()
	{
		return estudianteId;
	}

	/**
	 * Method 'setEstudianteId'
	 * 
	 * @param estudianteId
	 */
	public void setEstudianteId(long estudianteId)
	{
		this.estudianteId = estudianteId;
	}

	/**
	 * Method 'getNumExamen'
	 * 
	 * @return int
	 */
	public int getNumExamen()
	{
		return numExamen;
	}

	/**
	 * Method 'setNumExamen'
	 * 
	 * @param numExamen
	 */
	public void setNumExamen(int numExamen)
	{
		this.numExamen = numExamen;
	}

	/**
	 * Method 'getCalificacion'
	 * 
	 * @return float
	 */
	public float getCalificacion()
	{
		return calificacion;
	}

	/**
	 * Method 'setCalificacion'
	 * 
	 * @param calificacion
	 */
	public void setCalificacion(float calificacion)
	{
		this.calificacion = calificacion;
	}

	/**
	 * Method 'getAsignaturaId'
	 * 
	 * @return long
	 */
	public long getAsignaturaId()
	{
		return asignaturaId;
	}

	/**
	 * Method 'setAsignaturaId'
	 * 
	 * @param asignaturaId
	 */
	public void setAsignaturaId(long asignaturaId)
	{
		this.asignaturaId = asignaturaId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstudianteExtraordinario)) {
			return false;
		}
		
		final EstudianteExtraordinario _cast = (EstudianteExtraordinario) _other;
		if (estudianteId != _cast.estudianteId) {
			return false;
		}
		
		if (numExamen != _cast.numExamen) {
			return false;
		}
		
		if (calificacion != _cast.calificacion) {
			return false;
		}
		
		if (asignaturaId != _cast.asignaturaId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (estudianteId ^ (estudianteId >>> 32));
		_hashCode = 29 * _hashCode + numExamen;
		_hashCode = 29 * _hashCode + Float.floatToIntBits(calificacion);
		_hashCode = 29 * _hashCode + (int) (asignaturaId ^ (asignaturaId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EstudianteExtraordinarioPk
	 */
	public EstudianteExtraordinarioPk createPk()
	{
		return new EstudianteExtraordinarioPk(estudianteId, numExamen);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.EstudianteExtraordinario: " );
		ret.append( "estudianteId=" + estudianteId );
		ret.append( ", numExamen=" + numExamen );
		ret.append( ", calificacion=" + calificacion );
		ret.append( ", asignaturaId=" + asignaturaId );
		return ret.toString();
	}

}
