/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ESTUDIANTE_EXTRAORDINARIO table.
 */
public class EstudianteExtraordinarioPk implements Serializable
{
	protected long estudianteId;

	protected int numExamen;

	/** 
	 * This attribute represents whether the primitive attribute estudianteId is null.
	 */
	protected boolean estudianteIdNull;

	/** 
	 * This attribute represents whether the primitive attribute numExamen is null.
	 */
	protected boolean numExamenNull;

	/** 
	 * Sets the value of estudianteId
	 */
	public void setEstudianteId(long estudianteId)
	{
		this.estudianteId = estudianteId;
	}

	/** 
	 * Gets the value of estudianteId
	 */
	public long getEstudianteId()
	{
		return estudianteId;
	}

	/** 
	 * Sets the value of numExamen
	 */
	public void setNumExamen(int numExamen)
	{
		this.numExamen = numExamen;
	}

	/** 
	 * Gets the value of numExamen
	 */
	public int getNumExamen()
	{
		return numExamen;
	}

	/**
	 * Method 'EstudianteExtraordinarioPk'
	 * 
	 */
	public EstudianteExtraordinarioPk()
	{
	}

	/**
	 * Method 'EstudianteExtraordinarioPk'
	 * 
	 * @param estudianteId
	 * @param numExamen
	 */
	public EstudianteExtraordinarioPk(final long estudianteId, final int numExamen)
	{
		this.estudianteId = estudianteId;
		this.numExamen = numExamen;
	}

	/** 
	 * Sets the value of estudianteIdNull
	 */
	public void setEstudianteIdNull(boolean estudianteIdNull)
	{
		this.estudianteIdNull = estudianteIdNull;
	}

	/** 
	 * Gets the value of estudianteIdNull
	 */
	public boolean isEstudianteIdNull()
	{
		return estudianteIdNull;
	}

	/** 
	 * Sets the value of numExamenNull
	 */
	public void setNumExamenNull(boolean numExamenNull)
	{
		this.numExamenNull = numExamenNull;
	}

	/** 
	 * Gets the value of numExamenNull
	 */
	public boolean isNumExamenNull()
	{
		return numExamenNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstudianteExtraordinarioPk)) {
			return false;
		}
		
		final EstudianteExtraordinarioPk _cast = (EstudianteExtraordinarioPk) _other;
		if (estudianteId != _cast.estudianteId) {
			return false;
		}
		
		if (numExamen != _cast.numExamen) {
			return false;
		}
		
		if (estudianteIdNull != _cast.estudianteIdNull) {
			return false;
		}
		
		if (numExamenNull != _cast.numExamenNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (estudianteId ^ (estudianteId >>> 32));
		_hashCode = 29 * _hashCode + numExamen;
		_hashCode = 29 * _hashCode + (estudianteIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (numExamenNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.EstudianteExtraordinarioPk: " );
		ret.append( "estudianteId=" + estudianteId );
		ret.append( ", numExamen=" + numExamen );
		return ret.toString();
	}

}
