/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Horario implements Serializable
{
	/** 
	 * This attribute maps to the column HORARIO_ID in the HORARIO table.
	 */
	protected long horarioId;

	/** 
	 * This attribute maps to the column DIA_SEMANA in the HORARIO table.
	 */
	protected int diaSemana;

	/** 
	 * This attribute maps to the column HORA_INICIO in the HORARIO table.
	 */
	protected Date horaInicio;

	/** 
	 * This attribute maps to the column HORA_FIN in the HORARIO table.
	 */
	protected Date horaFin;

	/**
	 * Method 'Horario'
	 * 
	 */
	public Horario()
	{
	}

	/**
	 * Method 'getHorarioId'
	 * 
	 * @return long
	 */
	public long getHorarioId()
	{
		return horarioId;
	}

	/**
	 * Method 'setHorarioId'
	 * 
	 * @param horarioId
	 */
	public void setHorarioId(long horarioId)
	{
		this.horarioId = horarioId;
	}

	/**
	 * Method 'getDiaSemana'
	 * 
	 * @return int
	 */
	public int getDiaSemana()
	{
		return diaSemana;
	}

	/**
	 * Method 'setDiaSemana'
	 * 
	 * @param diaSemana
	 */
	public void setDiaSemana(int diaSemana)
	{
		this.diaSemana = diaSemana;
	}

	/**
	 * Method 'getHoraInicio'
	 * 
	 * @return Date
	 */
	public Date getHoraInicio()
	{
		return horaInicio;
	}

	/**
	 * Method 'setHoraInicio'
	 * 
	 * @param horaInicio
	 */
	public void setHoraInicio(Date horaInicio)
	{
		this.horaInicio = horaInicio;
	}

	/**
	 * Method 'getHoraFin'
	 * 
	 * @return Date
	 */
	public Date getHoraFin()
	{
		return horaFin;
	}

	/**
	 * Method 'setHoraFin'
	 * 
	 * @param horaFin
	 */
	public void setHoraFin(Date horaFin)
	{
		this.horaFin = horaFin;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Horario)) {
			return false;
		}
		
		final Horario _cast = (Horario) _other;
		if (horarioId != _cast.horarioId) {
			return false;
		}
		
		if (diaSemana != _cast.diaSemana) {
			return false;
		}
		
		if (horaInicio == null ? _cast.horaInicio != horaInicio : !horaInicio.equals( _cast.horaInicio )) {
			return false;
		}
		
		if (horaFin == null ? _cast.horaFin != horaFin : !horaFin.equals( _cast.horaFin )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (horarioId ^ (horarioId >>> 32));
		_hashCode = 29 * _hashCode + diaSemana;
		if (horaInicio != null) {
			_hashCode = 29 * _hashCode + horaInicio.hashCode();
		}
		
		if (horaFin != null) {
			_hashCode = 29 * _hashCode + horaFin.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return HorarioPk
	 */
	public HorarioPk createPk()
	{
		return new HorarioPk(horarioId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.Horario: " );
		ret.append( "horarioId=" + horarioId );
		ret.append( ", diaSemana=" + diaSemana );
		ret.append( ", horaInicio=" + horaInicio );
		ret.append( ", horaFin=" + horaFin );
		return ret.toString();
	}

}
