/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the HORARIO table.
 */
public class HorarioPk implements Serializable
{
	protected long horarioId;

	/** 
	 * This attribute represents whether the primitive attribute horarioId is null.
	 */
	protected boolean horarioIdNull;

	/** 
	 * Sets the value of horarioId
	 */
	public void setHorarioId(long horarioId)
	{
		this.horarioId = horarioId;
	}

	/** 
	 * Gets the value of horarioId
	 */
	public long getHorarioId()
	{
		return horarioId;
	}

	/**
	 * Method 'HorarioPk'
	 * 
	 */
	public HorarioPk()
	{
	}

	/**
	 * Method 'HorarioPk'
	 * 
	 * @param horarioId
	 */
	public HorarioPk(final long horarioId)
	{
		this.horarioId = horarioId;
	}

	/** 
	 * Sets the value of horarioIdNull
	 */
	public void setHorarioIdNull(boolean horarioIdNull)
	{
		this.horarioIdNull = horarioIdNull;
	}

	/** 
	 * Gets the value of horarioIdNull
	 */
	public boolean isHorarioIdNull()
	{
		return horarioIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof HorarioPk)) {
			return false;
		}
		
		final HorarioPk _cast = (HorarioPk) _other;
		if (horarioId != _cast.horarioId) {
			return false;
		}
		
		if (horarioIdNull != _cast.horarioIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (horarioId ^ (horarioId >>> 32));
		_hashCode = 29 * _hashCode + (horarioIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.HorarioPk: " );
		ret.append( "horarioId=" + horarioId );
		return ret.toString();
	}

}
