/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the PLAN_ESTUDIOS table.
 */
public class PlanEstudiosPk implements Serializable
{
	protected int planEstudiosId;

	/** 
	 * This attribute represents whether the primitive attribute planEstudiosId is null.
	 */
	protected boolean planEstudiosIdNull;

	/** 
	 * Sets the value of planEstudiosId
	 */
	public void setPlanEstudiosId(int planEstudiosId)
	{
		this.planEstudiosId = planEstudiosId;
	}

	/** 
	 * Gets the value of planEstudiosId
	 */
	public int getPlanEstudiosId()
	{
		return planEstudiosId;
	}

	/**
	 * Method 'PlanEstudiosPk'
	 * 
	 */
	public PlanEstudiosPk()
	{
	}

	/**
	 * Method 'PlanEstudiosPk'
	 * 
	 * @param planEstudiosId
	 */
	public PlanEstudiosPk(final int planEstudiosId)
	{
		this.planEstudiosId = planEstudiosId;
	}

	/** 
	 * Sets the value of planEstudiosIdNull
	 */
	public void setPlanEstudiosIdNull(boolean planEstudiosIdNull)
	{
		this.planEstudiosIdNull = planEstudiosIdNull;
	}

	/** 
	 * Gets the value of planEstudiosIdNull
	 */
	public boolean isPlanEstudiosIdNull()
	{
		return planEstudiosIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PlanEstudiosPk)) {
			return false;
		}
		
		final PlanEstudiosPk _cast = (PlanEstudiosPk) _other;
		if (planEstudiosId != _cast.planEstudiosId) {
			return false;
		}
		
		if (planEstudiosIdNull != _cast.planEstudiosIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + planEstudiosId;
		_hashCode = 29 * _hashCode + (planEstudiosIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.PlanEstudiosPk: " );
		ret.append( "planEstudiosId=" + planEstudiosId );
		return ret.toString();
	}

}
