/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class PlanEstudios implements Serializable
{
	/** 
	 * This attribute maps to the column PLAN_ESTUDIOS_ID in the PLAN_ESTUDIOS table.
	 */
	protected int planEstudiosId;

	/** 
	 * This attribute maps to the column CLAVE in the PLAN_ESTUDIOS table.
	 */
	protected String clave;

	/** 
	 * This attribute maps to the column FECHA_APROBACION in the PLAN_ESTUDIOS table.
	 */
	protected Date fechaAprobacion;

	/** 
	 * This attribute maps to the column FECHA_INICIO in the PLAN_ESTUDIOS table.
	 */
	protected Date fechaInicio;

	/** 
	 * This attribute maps to the column FECHA_FIN in the PLAN_ESTUDIOS table.
	 */
	protected Date fechaFin;

	/**
	 * Method 'PlanEstudios'
	 * 
	 */
	public PlanEstudios()
	{
	}

	/**
	 * Method 'getPlanEstudiosId'
	 * 
	 * @return int
	 */
	public int getPlanEstudiosId()
	{
		return planEstudiosId;
	}

	/**
	 * Method 'setPlanEstudiosId'
	 * 
	 * @param planEstudiosId
	 */
	public void setPlanEstudiosId(int planEstudiosId)
	{
		this.planEstudiosId = planEstudiosId;
	}

	/**
	 * Method 'getClave'
	 * 
	 * @return String
	 */
	public String getClave()
	{
		return clave;
	}

	/**
	 * Method 'setClave'
	 * 
	 * @param clave
	 */
	public void setClave(String clave)
	{
		this.clave = clave;
	}

	/**
	 * Method 'getFechaAprobacion'
	 * 
	 * @return Date
	 */
	public Date getFechaAprobacion()
	{
		return fechaAprobacion;
	}

	/**
	 * Method 'setFechaAprobacion'
	 * 
	 * @param fechaAprobacion
	 */
	public void setFechaAprobacion(Date fechaAprobacion)
	{
		this.fechaAprobacion = fechaAprobacion;
	}

	/**
	 * Method 'getFechaInicio'
	 * 
	 * @return Date
	 */
	public Date getFechaInicio()
	{
		return fechaInicio;
	}

	/**
	 * Method 'setFechaInicio'
	 * 
	 * @param fechaInicio
	 */
	public void setFechaInicio(Date fechaInicio)
	{
		this.fechaInicio = fechaInicio;
	}

	/**
	 * Method 'getFechaFin'
	 * 
	 * @return Date
	 */
	public Date getFechaFin()
	{
		return fechaFin;
	}

	/**
	 * Method 'setFechaFin'
	 * 
	 * @param fechaFin
	 */
	public void setFechaFin(Date fechaFin)
	{
		this.fechaFin = fechaFin;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PlanEstudios)) {
			return false;
		}
		
		final PlanEstudios _cast = (PlanEstudios) _other;
		if (planEstudiosId != _cast.planEstudiosId) {
			return false;
		}
		
		if (clave == null ? _cast.clave != clave : !clave.equals( _cast.clave )) {
			return false;
		}
		
		if (fechaAprobacion == null ? _cast.fechaAprobacion != fechaAprobacion : !fechaAprobacion.equals( _cast.fechaAprobacion )) {
			return false;
		}
		
		if (fechaInicio == null ? _cast.fechaInicio != fechaInicio : !fechaInicio.equals( _cast.fechaInicio )) {
			return false;
		}
		
		if (fechaFin == null ? _cast.fechaFin != fechaFin : !fechaFin.equals( _cast.fechaFin )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + planEstudiosId;
		if (clave != null) {
			_hashCode = 29 * _hashCode + clave.hashCode();
		}
		
		if (fechaAprobacion != null) {
			_hashCode = 29 * _hashCode + fechaAprobacion.hashCode();
		}
		
		if (fechaInicio != null) {
			_hashCode = 29 * _hashCode + fechaInicio.hashCode();
		}
		
		if (fechaFin != null) {
			_hashCode = 29 * _hashCode + fechaFin.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PlanEstudiosPk
	 */
	public PlanEstudiosPk createPk()
	{
		return new PlanEstudiosPk(planEstudiosId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.PlanEstudios: " );
		ret.append( "planEstudiosId=" + planEstudiosId );
		ret.append( ", clave=" + clave );
		ret.append( ", fechaAprobacion=" + fechaAprobacion );
		ret.append( ", fechaInicio=" + fechaInicio );
		ret.append( ", fechaFin=" + fechaFin );
		return ret.toString();
	}

}
