/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the PROFESOR table.
 */
public class ProfesorPk implements Serializable
{
	protected long profesorId;

	/** 
	 * This attribute represents whether the primitive attribute profesorId is null.
	 */
	protected boolean profesorIdNull;

	/** 
	 * Sets the value of profesorId
	 */
	public void setProfesorId(long profesorId)
	{
		this.profesorId = profesorId;
	}

	/** 
	 * Gets the value of profesorId
	 */
	public long getProfesorId()
	{
		return profesorId;
	}

	/**
	 * Method 'ProfesorPk'
	 * 
	 */
	public ProfesorPk()
	{
	}

	/**
	 * Method 'ProfesorPk'
	 * 
	 * @param profesorId
	 */
	public ProfesorPk(final long profesorId)
	{
		this.profesorId = profesorId;
	}

	/** 
	 * Sets the value of profesorIdNull
	 */
	public void setProfesorIdNull(boolean profesorIdNull)
	{
		this.profesorIdNull = profesorIdNull;
	}

	/** 
	 * Gets the value of profesorIdNull
	 */
	public boolean isProfesorIdNull()
	{
		return profesorIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProfesorPk)) {
			return false;
		}
		
		final ProfesorPk _cast = (ProfesorPk) _other;
		if (profesorId != _cast.profesorId) {
			return false;
		}
		
		if (profesorIdNull != _cast.profesorIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (profesorId ^ (profesorId >>> 32));
		_hashCode = 29 * _hashCode + (profesorIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.ProfesorPk: " );
		ret.append( "profesorId=" + profesorId );
		return ret.toString();
	}

}
