/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Profesor implements Serializable
{
	/** 
	 * This attribute maps to the column PROFESOR_ID in the PROFESOR table.
	 */
	protected long profesorId;

	/** 
	 * This attribute maps to the column NOMBRE in the PROFESOR table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column APELLIDO_PATERNO in the PROFESOR table.
	 */
	protected String apellidoPaterno;

	/** 
	 * This attribute maps to the column APELLIDO_MATERNO in the PROFESOR table.
	 */
	protected String apellidoMaterno;

	/** 
	 * This attribute maps to the column RFC in the PROFESOR table.
	 */
	protected String rfc;

	/** 
	 * This attribute maps to the column FECHA_NACIMIENTO in the PROFESOR table.
	 */
	protected Date fechaNacimiento;

	/**
	 * Method 'Profesor'
	 * 
	 */
	public Profesor()
	{
	}

	/**
	 * Method 'getProfesorId'
	 * 
	 * @return long
	 */
	public long getProfesorId()
	{
		return profesorId;
	}

	/**
	 * Method 'setProfesorId'
	 * 
	 * @param profesorId
	 */
	public void setProfesorId(long profesorId)
	{
		this.profesorId = profesorId;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getApellidoPaterno'
	 * 
	 * @return String
	 */
	public String getApellidoPaterno()
	{
		return apellidoPaterno;
	}

	/**
	 * Method 'setApellidoPaterno'
	 * 
	 * @param apellidoPaterno
	 */
	public void setApellidoPaterno(String apellidoPaterno)
	{
		this.apellidoPaterno = apellidoPaterno;
	}

	/**
	 * Method 'getApellidoMaterno'
	 * 
	 * @return String
	 */
	public String getApellidoMaterno()
	{
		return apellidoMaterno;
	}

	/**
	 * Method 'setApellidoMaterno'
	 * 
	 * @param apellidoMaterno
	 */
	public void setApellidoMaterno(String apellidoMaterno)
	{
		this.apellidoMaterno = apellidoMaterno;
	}

	/**
	 * Method 'getRfc'
	 * 
	 * @return String
	 */
	public String getRfc()
	{
		return rfc;
	}

	/**
	 * Method 'setRfc'
	 * 
	 * @param rfc
	 */
	public void setRfc(String rfc)
	{
		this.rfc = rfc;
	}

	/**
	 * Method 'getFechaNacimiento'
	 * 
	 * @return Date
	 */
	public Date getFechaNacimiento()
	{
		return fechaNacimiento;
	}

	/**
	 * Method 'setFechaNacimiento'
	 * 
	 * @param fechaNacimiento
	 */
	public void setFechaNacimiento(Date fechaNacimiento)
	{
		this.fechaNacimiento = fechaNacimiento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Profesor)) {
			return false;
		}
		
		final Profesor _cast = (Profesor) _other;
		if (profesorId != _cast.profesorId) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (apellidoPaterno == null ? _cast.apellidoPaterno != apellidoPaterno : !apellidoPaterno.equals( _cast.apellidoPaterno )) {
			return false;
		}
		
		if (apellidoMaterno == null ? _cast.apellidoMaterno != apellidoMaterno : !apellidoMaterno.equals( _cast.apellidoMaterno )) {
			return false;
		}
		
		if (rfc == null ? _cast.rfc != rfc : !rfc.equals( _cast.rfc )) {
			return false;
		}
		
		if (fechaNacimiento == null ? _cast.fechaNacimiento != fechaNacimiento : !fechaNacimiento.equals( _cast.fechaNacimiento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (profesorId ^ (profesorId >>> 32));
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (apellidoPaterno != null) {
			_hashCode = 29 * _hashCode + apellidoPaterno.hashCode();
		}
		
		if (apellidoMaterno != null) {
			_hashCode = 29 * _hashCode + apellidoMaterno.hashCode();
		}
		
		if (rfc != null) {
			_hashCode = 29 * _hashCode + rfc.hashCode();
		}
		
		if (fechaNacimiento != null) {
			_hashCode = 29 * _hashCode + fechaNacimiento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProfesorPk
	 */
	public ProfesorPk createPk()
	{
		return new ProfesorPk(profesorId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.Profesor: " );
		ret.append( "profesorId=" + profesorId );
		ret.append( ", nombre=" + nombre );
		ret.append( ", apellidoPaterno=" + apellidoPaterno );
		ret.append( ", apellidoMaterno=" + apellidoMaterno );
		ret.append( ", rfc=" + rfc );
		ret.append( ", fechaNacimiento=" + fechaNacimiento );
		return ret.toString();
	}

}
