/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Semestre implements Serializable
{
	/** 
	 * This attribute maps to the column SEMESTRE_ID in the SEMESTRE table.
	 */
	protected long semestreId;

	/** 
	 * This attribute maps to the column ANIO in the SEMESTRE table.
	 */
	protected int anio;

	/** 
	 * This attribute maps to the column PERIODO in the SEMESTRE table.
	 */
	protected int periodo;

	/** 
	 * This attribute maps to the column FECHA_INICIO in the SEMESTRE table.
	 */
	protected Date fechaInicio;

	/** 
	 * This attribute maps to the column FECHA_FIN in the SEMESTRE table.
	 */
	protected Date fechaFin;

	/**
	 * Method 'Semestre'
	 * 
	 */
	public Semestre()
	{
	}

	/**
	 * Method 'getSemestreId'
	 * 
	 * @return long
	 */
	public long getSemestreId()
	{
		return semestreId;
	}

	/**
	 * Method 'setSemestreId'
	 * 
	 * @param semestreId
	 */
	public void setSemestreId(long semestreId)
	{
		this.semestreId = semestreId;
	}

	/**
	 * Method 'getAnio'
	 * 
	 * @return int
	 */
	public int getAnio()
	{
		return anio;
	}

	/**
	 * Method 'setAnio'
	 * 
	 * @param anio
	 */
	public void setAnio(int anio)
	{
		this.anio = anio;
	}

	/**
	 * Method 'getPeriodo'
	 * 
	 * @return int
	 */
	public int getPeriodo()
	{
		return periodo;
	}

	/**
	 * Method 'setPeriodo'
	 * 
	 * @param periodo
	 */
	public void setPeriodo(int periodo)
	{
		this.periodo = periodo;
	}

	/**
	 * Method 'getFechaInicio'
	 * 
	 * @return Date
	 */
	public Date getFechaInicio()
	{
		return fechaInicio;
	}

	/**
	 * Method 'setFechaInicio'
	 * 
	 * @param fechaInicio
	 */
	public void setFechaInicio(Date fechaInicio)
	{
		this.fechaInicio = fechaInicio;
	}

	/**
	 * Method 'getFechaFin'
	 * 
	 * @return Date
	 */
	public Date getFechaFin()
	{
		return fechaFin;
	}

	/**
	 * Method 'setFechaFin'
	 * 
	 * @param fechaFin
	 */
	public void setFechaFin(Date fechaFin)
	{
		this.fechaFin = fechaFin;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Semestre)) {
			return false;
		}
		
		final Semestre _cast = (Semestre) _other;
		if (semestreId != _cast.semestreId) {
			return false;
		}
		
		if (anio != _cast.anio) {
			return false;
		}
		
		if (periodo != _cast.periodo) {
			return false;
		}
		
		if (fechaInicio == null ? _cast.fechaInicio != fechaInicio : !fechaInicio.equals( _cast.fechaInicio )) {
			return false;
		}
		
		if (fechaFin == null ? _cast.fechaFin != fechaFin : !fechaFin.equals( _cast.fechaFin )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (semestreId ^ (semestreId >>> 32));
		_hashCode = 29 * _hashCode + anio;
		_hashCode = 29 * _hashCode + periodo;
		if (fechaInicio != null) {
			_hashCode = 29 * _hashCode + fechaInicio.hashCode();
		}
		
		if (fechaFin != null) {
			_hashCode = 29 * _hashCode + fechaFin.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SemestrePk
	 */
	public SemestrePk createPk()
	{
		return new SemestrePk(semestreId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.Semestre: " );
		ret.append( "semestreId=" + semestreId );
		ret.append( ", anio=" + anio );
		ret.append( ", periodo=" + periodo );
		ret.append( ", fechaInicio=" + fechaInicio );
		ret.append( ", fechaFin=" + fechaFin );
		return ret.toString();
	}

}
