/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the SEMESTRE table.
 */
public class SemestrePk implements Serializable
{
	protected long semestreId;

	/** 
	 * This attribute represents whether the primitive attribute semestreId is null.
	 */
	protected boolean semestreIdNull;

	/** 
	 * Sets the value of semestreId
	 */
	public void setSemestreId(long semestreId)
	{
		this.semestreId = semestreId;
	}

	/** 
	 * Gets the value of semestreId
	 */
	public long getSemestreId()
	{
		return semestreId;
	}

	/**
	 * Method 'SemestrePk'
	 * 
	 */
	public SemestrePk()
	{
	}

	/**
	 * Method 'SemestrePk'
	 * 
	 * @param semestreId
	 */
	public SemestrePk(final long semestreId)
	{
		this.semestreId = semestreId;
	}

	/** 
	 * Sets the value of semestreIdNull
	 */
	public void setSemestreIdNull(boolean semestreIdNull)
	{
		this.semestreIdNull = semestreIdNull;
	}

	/** 
	 * Gets the value of semestreIdNull
	 */
	public boolean isSemestreIdNull()
	{
		return semestreIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SemestrePk)) {
			return false;
		}
		
		final SemestrePk _cast = (SemestrePk) _other;
		if (semestreId != _cast.semestreId) {
			return false;
		}
		
		if (semestreIdNull != _cast.semestreIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (semestreId ^ (semestreId >>> 32));
		_hashCode = 29 * _hashCode + (semestreIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.escuela.escuelaOracle.dto.SemestrePk: " );
		ret.append( "semestreId=" + semestreId );
		return ret.toString();
	}

}
