/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.factory;

import java.sql.Connection;
import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.jdbc.*;

public class EstudianteExtraordinarioDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return EstudianteExtraordinarioDao
	 */
	public static EstudianteExtraordinarioDao create()
	{
		return new EstudianteExtraordinarioDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return EstudianteExtraordinarioDao
	 */
	public static EstudianteExtraordinarioDao create(Connection conn)
	{
		return new EstudianteExtraordinarioDaoImpl( conn );
	}

}
