/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface AsignaturaDao
{
	/** 
	 * Inserts a new row in the ASIGNATURA table.
	 */
	public AsignaturaPk insert(Asignatura dto) throws AsignaturaDaoException;

	/** 
	 * Updates a single row in the ASIGNATURA table.
	 */
	public void update(AsignaturaPk pk, Asignatura dto) throws AsignaturaDaoException;

	/** 
	 * Deletes a single row in the ASIGNATURA table.
	 */
	public void delete(AsignaturaPk pk) throws AsignaturaDaoException;

	/** 
	 * Returns the rows from the ASIGNATURA table that matches the specified primary-key value.
	 */
	public Asignatura findByPrimaryKey(AsignaturaPk pk) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Asignatura findByPrimaryKey(long asignaturaId) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria ''.
	 */
	public Asignatura[] findAll() throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_REQUERIDA_ID = :asignaturaRequeridaId'.
	 */
	public Asignatura[] findByAsignatura(long asignaturaRequeridaId) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Asignatura[] findByPlanEstudios(int planEstudiosId) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Asignatura[] findWhereAsignaturaIdEquals(long asignaturaId) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Asignatura[] findWhereNombreEquals(String nombre) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'CREDITOS = :creditos'.
	 */
	public Asignatura[] findWhereCreditosEquals(int creditos) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_REQUERIDA_ID = :asignaturaRequeridaId'.
	 */
	public Asignatura[] findWhereAsignaturaRequeridaIdEquals(long asignaturaRequeridaId) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Asignatura[] findWherePlanEstudiosIdEquals(int planEstudiosId) throws AsignaturaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ASIGNATURA table that match the specified arbitrary SQL statement
	 */
	public Asignatura[] findByDynamicSelect(String sql, Object[] sqlParams) throws AsignaturaDaoException;

	/** 
	 * Returns all rows from the ASIGNATURA table that match the specified arbitrary SQL statement
	 */
	public Asignatura[] findByDynamicWhere(String sql, Object[] sqlParams) throws AsignaturaDaoException;

}
