/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface CursoDao
{
	/** 
	 * Inserts a new row in the CURSO table.
	 */
	public CursoPk insert(Curso dto) throws CursoDaoException;

	/** 
	 * Updates a single row in the CURSO table.
	 */
	public void update(CursoPk pk, Curso dto) throws CursoDaoException;

	/** 
	 * Deletes a single row in the CURSO table.
	 */
	public void delete(CursoPk pk) throws CursoDaoException;

	/** 
	 * Returns the rows from the CURSO table that matches the specified primary-key value.
	 */
	public Curso findByPrimaryKey(CursoPk pk) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public Curso findByPrimaryKey(long cursoId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria ''.
	 */
	public Curso[] findAll() throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Curso[] findByAsignatura(long asignaturaId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Curso[] findByProfesor(long profesorId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Curso[] findBySemestre(long semestreId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public Curso[] findWhereCursoIdEquals(long cursoId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CUPO_MAXIMO = :cupoMaximo'.
	 */
	public Curso[] findWhereCupoMaximoEquals(int cupoMaximo) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Curso[] findWhereProfesorIdEquals(long profesorId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Curso[] findWhereAsignaturaIdEquals(long asignaturaId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Curso[] findWhereSemestreIdEquals(long semestreId) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CLAVE_GRUPO = :claveGrupo'.
	 */
	public Curso[] findWhereClaveGrupoEquals(String claveGrupo) throws CursoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the CURSO table that match the specified arbitrary SQL statement
	 */
	public Curso[] findByDynamicSelect(String sql, Object[] sqlParams) throws CursoDaoException;

	/** 
	 * Returns all rows from the CURSO table that match the specified arbitrary SQL statement
	 */
	public Curso[] findByDynamicWhere(String sql, Object[] sqlParams) throws CursoDaoException;

}
