/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface CursoHorarioDao
{
	/** 
	 * Inserts a new row in the CURSO_HORARIO table.
	 */
	public CursoHorarioPk insert(CursoHorario dto) throws CursoHorarioDaoException;

	/** 
	 * Updates a single row in the CURSO_HORARIO table.
	 */
	public void update(CursoHorarioPk pk, CursoHorario dto) throws CursoHorarioDaoException;

	/** 
	 * Deletes a single row in the CURSO_HORARIO table.
	 */
	public void delete(CursoHorarioPk pk) throws CursoHorarioDaoException;

	/** 
	 * Returns the rows from the CURSO_HORARIO table that matches the specified primary-key value.
	 */
	public CursoHorario findByPrimaryKey(CursoHorarioPk pk) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_HORARIO_ID = :cursoHorarioId'.
	 */
	public CursoHorario findByPrimaryKey(long cursoHorarioId) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria ''.
	 */
	public CursoHorario[] findAll() throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public CursoHorario[] findByCurso(long cursoId) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public CursoHorario[] findByHorario(long horarioId) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_HORARIO_ID = :cursoHorarioId'.
	 */
	public CursoHorario[] findWhereCursoHorarioIdEquals(long cursoHorarioId) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public CursoHorario[] findWhereCursoIdEquals(long cursoId) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public CursoHorario[] findWhereHorarioIdEquals(long horarioId) throws CursoHorarioDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the specified arbitrary SQL statement
	 */
	public CursoHorario[] findByDynamicSelect(String sql, Object[] sqlParams) throws CursoHorarioDaoException;

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the specified arbitrary SQL statement
	 */
	public CursoHorario[] findByDynamicWhere(String sql, Object[] sqlParams) throws CursoHorarioDaoException;

}
