/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface EstudianteDao
{
	/** 
	 * Inserts a new row in the ESTUDIANTE table.
	 */
	public EstudiantePk insert(Estudiante dto) throws EstudianteDaoException;

	/** 
	 * Updates a single row in the ESTUDIANTE table.
	 */
	public void update(EstudiantePk pk, Estudiante dto) throws EstudianteDaoException;

	/** 
	 * Deletes a single row in the ESTUDIANTE table.
	 */
	public void delete(EstudiantePk pk) throws EstudianteDaoException;

	/** 
	 * Returns the rows from the ESTUDIANTE table that matches the specified primary-key value.
	 */
	public Estudiante findByPrimaryKey(EstudiantePk pk) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public Estudiante findByPrimaryKey(long estudianteId) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria ''.
	 */
	public Estudiante[] findAll() throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Estudiante[] findByPlanEstudios(int planEstudiosId) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public Estudiante[] findWhereEstudianteIdEquals(long estudianteId) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Estudiante[] findWhereNombreEquals(String nombre) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'APELLIDO_PATERNO = :apellidoPaterno'.
	 */
	public Estudiante[] findWhereApellidoPaternoEquals(String apellidoPaterno) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'APELLIDO_MATERNO = :apellidoMaterno'.
	 */
	public Estudiante[] findWhereApellidoMaternoEquals(String apellidoMaterno) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'FECHA_NACIMIENTO = :fechaNacimiento'.
	 */
	public Estudiante[] findWhereFechaNacimientoEquals(Date fechaNacimiento) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'FOTOGRAFIA = :fotografia'.
	 */
	public Estudiante[] findWhereFotografiaEquals(byte[] fotografia) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Estudiante[] findWherePlanEstudiosIdEquals(int planEstudiosId) throws EstudianteDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the specified arbitrary SQL statement
	 */
	public Estudiante[] findByDynamicSelect(String sql, Object[] sqlParams) throws EstudianteDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the specified arbitrary SQL statement
	 */
	public Estudiante[] findByDynamicWhere(String sql, Object[] sqlParams) throws EstudianteDaoException;

}
