/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface EstudianteInscritoDao
{
	/** 
	 * Inserts a new row in the ESTUDIANTE_INSCRITO table.
	 */
	public EstudianteInscritoPk insert(EstudianteInscrito dto) throws EstudianteInscritoDaoException;

	/** 
	 * Updates a single row in the ESTUDIANTE_INSCRITO table.
	 */
	public void update(EstudianteInscritoPk pk, EstudianteInscrito dto) throws EstudianteInscritoDaoException;

	/** 
	 * Deletes a single row in the ESTUDIANTE_INSCRITO table.
	 */
	public void delete(EstudianteInscritoPk pk) throws EstudianteInscritoDaoException;

	/** 
	 * Returns the rows from the ESTUDIANTE_INSCRITO table that matches the specified primary-key value.
	 */
	public EstudianteInscrito findByPrimaryKey(EstudianteInscritoPk pk) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_INSCRITO_ID = :estudianteInscritoId'.
	 */
	public EstudianteInscrito findByPrimaryKey(long estudianteInscritoId) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria ''.
	 */
	public EstudianteInscrito[] findAll() throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public EstudianteInscrito[] findByCurso(long cursoId) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public EstudianteInscrito[] findByEstudiante(long estudianteId) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_INSCRITO_ID = :estudianteInscritoId'.
	 */
	public EstudianteInscrito[] findWhereEstudianteInscritoIdEquals(long estudianteInscritoId) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public EstudianteInscrito[] findWhereCursoIdEquals(long cursoId) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public EstudianteInscrito[] findWhereEstudianteIdEquals(long estudianteId) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'CALIFICACION = :calificacion'.
	 */
	public EstudianteInscrito[] findWhereCalificacionEquals(int calificacion) throws EstudianteInscritoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the specified arbitrary SQL statement
	 */
	public EstudianteInscrito[] findByDynamicSelect(String sql, Object[] sqlParams) throws EstudianteInscritoDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the specified arbitrary SQL statement
	 */
	public EstudianteInscrito[] findByDynamicWhere(String sql, Object[] sqlParams) throws EstudianteInscritoDaoException;

}
