/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface EstudianteExtraordinarioDao
{
	/** 
	 * Inserts a new row in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	public EstudianteExtraordinarioPk insert(EstudianteExtraordinario dto) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Updates a single row in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	public void update(EstudianteExtraordinarioPk pk, EstudianteExtraordinario dto) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Deletes a single row in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	public void delete(EstudianteExtraordinarioPk pk) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns the rows from the ESTUDIANTE_EXTRAORDINARIO table that matches the specified primary-key value.
	 */
	public EstudianteExtraordinario findByPrimaryKey(EstudianteExtraordinarioPk pk) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ESTUDIANTE_ID = :estudianteId AND NUM_EXAMEN = :numExamen'.
	 */
	public EstudianteExtraordinario findByPrimaryKey(long estudianteId, int numExamen) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria ''.
	 */
	public EstudianteExtraordinario[] findAll() throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public EstudianteExtraordinario[] findByAsignatura(long asignaturaId) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public EstudianteExtraordinario[] findWhereEstudianteIdEquals(long estudianteId) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'NUM_EXAMEN = :numExamen'.
	 */
	public EstudianteExtraordinario[] findWhereNumExamenEquals(int numExamen) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'CALIFICACION = :calificacion'.
	 */
	public EstudianteExtraordinario[] findWhereCalificacionEquals(float calificacion) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public EstudianteExtraordinario[] findWhereAsignaturaIdEquals(long asignaturaId) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the specified arbitrary SQL statement
	 */
	public EstudianteExtraordinario[] findByDynamicSelect(String sql, Object[] sqlParams) throws EstudianteExtraordinarioDaoException;

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the specified arbitrary SQL statement
	 */
	public EstudianteExtraordinario[] findByDynamicWhere(String sql, Object[] sqlParams) throws EstudianteExtraordinarioDaoException;

}
