/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface HorarioDao
{
	/** 
	 * Inserts a new row in the HORARIO table.
	 */
	public HorarioPk insert(Horario dto) throws HorarioDaoException;

	/** 
	 * Updates a single row in the HORARIO table.
	 */
	public void update(HorarioPk pk, Horario dto) throws HorarioDaoException;

	/** 
	 * Deletes a single row in the HORARIO table.
	 */
	public void delete(HorarioPk pk) throws HorarioDaoException;

	/** 
	 * Returns the rows from the HORARIO table that matches the specified primary-key value.
	 */
	public Horario findByPrimaryKey(HorarioPk pk) throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public Horario findByPrimaryKey(long horarioId) throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the criteria ''.
	 */
	public Horario[] findAll() throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public Horario[] findWhereHorarioIdEquals(long horarioId) throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'DIA_SEMANA = :diaSemana'.
	 */
	public Horario[] findWhereDiaSemanaEquals(int diaSemana) throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORA_INICIO = :horaInicio'.
	 */
	public Horario[] findWhereHoraInicioEquals(Date horaInicio) throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORA_FIN = :horaFin'.
	 */
	public Horario[] findWhereHoraFinEquals(Date horaFin) throws HorarioDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the HORARIO table that match the specified arbitrary SQL statement
	 */
	public Horario[] findByDynamicSelect(String sql, Object[] sqlParams) throws HorarioDaoException;

	/** 
	 * Returns all rows from the HORARIO table that match the specified arbitrary SQL statement
	 */
	public Horario[] findByDynamicWhere(String sql, Object[] sqlParams) throws HorarioDaoException;

}
