/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface PlanEstudiosDao
{
	/** 
	 * Inserts a new row in the PLAN_ESTUDIOS table.
	 */
	public PlanEstudiosPk insert(PlanEstudios dto) throws PlanEstudiosDaoException;

	/** 
	 * Updates a single row in the PLAN_ESTUDIOS table.
	 */
	public void update(PlanEstudiosPk pk, PlanEstudios dto) throws PlanEstudiosDaoException;

	/** 
	 * Deletes a single row in the PLAN_ESTUDIOS table.
	 */
	public void delete(PlanEstudiosPk pk) throws PlanEstudiosDaoException;

	/** 
	 * Returns the rows from the PLAN_ESTUDIOS table that matches the specified primary-key value.
	 */
	public PlanEstudios findByPrimaryKey(PlanEstudiosPk pk) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public PlanEstudios findByPrimaryKey(int planEstudiosId) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria ''.
	 */
	public PlanEstudios[] findAll() throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public PlanEstudios[] findWherePlanEstudiosIdEquals(int planEstudiosId) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'CLAVE = :clave'.
	 */
	public PlanEstudios[] findWhereClaveEquals(String clave) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'FECHA_APROBACION = :fechaAprobacion'.
	 */
	public PlanEstudios[] findWhereFechaAprobacionEquals(Date fechaAprobacion) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'FECHA_INICIO = :fechaInicio'.
	 */
	public PlanEstudios[] findWhereFechaInicioEquals(Date fechaInicio) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'FECHA_FIN = :fechaFin'.
	 */
	public PlanEstudios[] findWhereFechaFinEquals(Date fechaFin) throws PlanEstudiosDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the specified arbitrary SQL statement
	 */
	public PlanEstudios[] findByDynamicSelect(String sql, Object[] sqlParams) throws PlanEstudiosDaoException;

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the specified arbitrary SQL statement
	 */
	public PlanEstudios[] findByDynamicWhere(String sql, Object[] sqlParams) throws PlanEstudiosDaoException;

}
