/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface ProfesorDao
{
	/** 
	 * Inserts a new row in the PROFESOR table.
	 */
	public ProfesorPk insert(Profesor dto) throws ProfesorDaoException;

	/** 
	 * Updates a single row in the PROFESOR table.
	 */
	public void update(ProfesorPk pk, Profesor dto) throws ProfesorDaoException;

	/** 
	 * Deletes a single row in the PROFESOR table.
	 */
	public void delete(ProfesorPk pk) throws ProfesorDaoException;

	/** 
	 * Returns the rows from the PROFESOR table that matches the specified primary-key value.
	 */
	public Profesor findByPrimaryKey(ProfesorPk pk) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Profesor findByPrimaryKey(long profesorId) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria ''.
	 */
	public Profesor[] findAll() throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Profesor[] findWhereProfesorIdEquals(long profesorId) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Profesor[] findWhereNombreEquals(String nombre) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'APELLIDO_PATERNO = :apellidoPaterno'.
	 */
	public Profesor[] findWhereApellidoPaternoEquals(String apellidoPaterno) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'APELLIDO_MATERNO = :apellidoMaterno'.
	 */
	public Profesor[] findWhereApellidoMaternoEquals(String apellidoMaterno) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'RFC = :rfc'.
	 */
	public Profesor[] findWhereRfcEquals(String rfc) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'FECHA_NACIMIENTO = :fechaNacimiento'.
	 */
	public Profesor[] findWhereFechaNacimientoEquals(Date fechaNacimiento) throws ProfesorDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the PROFESOR table that match the specified arbitrary SQL statement
	 */
	public Profesor[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProfesorDaoException;

	/** 
	 * Returns all rows from the PROFESOR table that match the specified arbitrary SQL statement
	 */
	public Profesor[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProfesorDaoException;

}
