/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface SemestreDao
{
	/** 
	 * Inserts a new row in the SEMESTRE table.
	 */
	public SemestrePk insert(Semestre dto) throws SemestreDaoException;

	/** 
	 * Updates a single row in the SEMESTRE table.
	 */
	public void update(SemestrePk pk, Semestre dto) throws SemestreDaoException;

	/** 
	 * Deletes a single row in the SEMESTRE table.
	 */
	public void delete(SemestrePk pk) throws SemestreDaoException;

	/** 
	 * Returns the rows from the SEMESTRE table that matches the specified primary-key value.
	 */
	public Semestre findByPrimaryKey(SemestrePk pk) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Semestre findByPrimaryKey(long semestreId) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria ''.
	 */
	public Semestre[] findAll() throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Semestre[] findWhereSemestreIdEquals(long semestreId) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'ANIO = :anio'.
	 */
	public Semestre[] findWhereAnioEquals(int anio) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'PERIODO = :periodo'.
	 */
	public Semestre[] findWherePeriodoEquals(int periodo) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'FECHA_INICIO = :fechaInicio'.
	 */
	public Semestre[] findWhereFechaInicioEquals(Date fechaInicio) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'FECHA_FIN = :fechaFin'.
	 */
	public Semestre[] findWhereFechaFinEquals(Date fechaFin) throws SemestreDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the SEMESTRE table that match the specified arbitrary SQL statement
	 */
	public Semestre[] findByDynamicSelect(String sql, Object[] sqlParams) throws SemestreDaoException;

	/** 
	 * Returns all rows from the SEMESTRE table that match the specified arbitrary SQL statement
	 */
	public Semestre[] findByDynamicWhere(String sql, Object[] sqlParams) throws SemestreDaoException;

}
