/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.dao;

import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;

public interface UsuarioDao
{
	/** 
	 * Inserts a new row in the USUARIO table.
	 */
	public UsuarioPk insert(Usuario dto) throws UsuarioDaoException;

	/** 
	 * Updates a single row in the USUARIO table.
	 */
	public void update(UsuarioPk pk, Usuario dto) throws UsuarioDaoException;

	/** 
	 * Deletes a single row in the USUARIO table.
	 */
	public void delete(UsuarioPk pk) throws UsuarioDaoException;

	/** 
	 * Returns the rows from the USUARIO table that matches the specified primary-key value.
	 */
	public Usuario findByPrimaryKey(UsuarioPk pk) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the USUARIO table that match the criteria 'ID_USUARIO = :idUsuario'.
	 */
	public Usuario findByPrimaryKey(long idUsuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the USUARIO table that match the criteria ''.
	 */
	public Usuario[] findAll() throws UsuarioDaoException;

	/** 
	 * Returns all rows from the USUARIO table that match the criteria 'ID_USUARIO = :idUsuario'.
	 */
	public Usuario[] findWhereIdUsuarioEquals(long idUsuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the USUARIO table that match the criteria 'USUARIO = :usuario'.
	 */
	public Usuario[] findWhereUsuarioEquals(String usuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the USUARIO table that match the criteria 'PASSWORD = :password'.
	 */
	public Usuario[] findWherePasswordEquals(String password) throws UsuarioDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the USUARIO table that match the specified arbitrary SQL statement
	 */
	public Usuario[] findByDynamicSelect(String sql, Object[] sqlParams) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the USUARIO table that match the specified arbitrary SQL statement
	 */
	public Usuario[] findByDynamicWhere(String sql, Object[] sqlParams) throws UsuarioDaoException;

}
