/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.AsignaturaDao;
import com.escuela.escuelaOracle.dto.Asignatura;
import com.escuela.escuelaOracle.exceptions.AsignaturaDaoException;
import com.escuela.escuelaOracle.factory.AsignaturaDaoFactory;

public class AsignaturaDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByAsignatura(0);
		// findByPlanEstudios(0);
		// findWhereAsignaturaIdEquals(0);
		// findWhereNombreEquals("");
		// findWhereCreditosEquals(0);
		// findWhereAsignaturaRequeridaIdEquals(0);
		// findWherePlanEstudiosIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByAsignatura'
	 * 
	 * @param asignaturaRequeridaId
	 */
	public static void findByAsignatura(long asignaturaRequeridaId)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findByAsignatura(asignaturaRequeridaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByPlanEstudios'
	 * 
	 * @param planEstudiosId
	 */
	public static void findByPlanEstudios(int planEstudiosId)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findByPlanEstudios(planEstudiosId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAsignaturaIdEquals'
	 * 
	 * @param asignaturaId
	 */
	public static void findWhereAsignaturaIdEquals(long asignaturaId)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findWhereAsignaturaIdEquals(asignaturaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreditosEquals'
	 * 
	 * @param creditos
	 */
	public static void findWhereCreditosEquals(int creditos)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findWhereCreditosEquals(creditos);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAsignaturaRequeridaIdEquals'
	 * 
	 * @param asignaturaRequeridaId
	 */
	public static void findWhereAsignaturaRequeridaIdEquals(long asignaturaRequeridaId)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findWhereAsignaturaRequeridaIdEquals(asignaturaRequeridaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePlanEstudiosIdEquals'
	 * 
	 * @param planEstudiosId
	 */
	public static void findWherePlanEstudiosIdEquals(int planEstudiosId)
	{
		try {
			AsignaturaDao _dao = getAsignaturaDao();
			Asignatura _result[] = _dao.findWherePlanEstudiosIdEquals(planEstudiosId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getAsignaturaDao'
	 * 
	 * @return AsignaturaDao
	 */
	public static AsignaturaDao getAsignaturaDao()
	{
		return AsignaturaDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Asignatura dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getAsignaturaId() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getCreditos() );
		buf.append( ", " );
		buf.append( dto.getAsignaturaRequeridaId() );
		buf.append( ", " );
		buf.append( dto.getPlanEstudiosId() );
		System.out.println( buf.toString() );
	}

}
