/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.CursoHorarioDao;
import com.escuela.escuelaOracle.dto.CursoHorario;
import com.escuela.escuelaOracle.exceptions.CursoHorarioDaoException;
import com.escuela.escuelaOracle.factory.CursoHorarioDaoFactory;

public class CursoHorarioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByCurso(0);
		// findByHorario(0);
		// findWhereCursoHorarioIdEquals(0);
		// findWhereCursoIdEquals(0);
		// findWhereHorarioIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CursoHorarioDao _dao = getCursoHorarioDao();
			CursoHorario _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCurso'
	 * 
	 * @param cursoId
	 */
	public static void findByCurso(long cursoId)
	{
		try {
			CursoHorarioDao _dao = getCursoHorarioDao();
			CursoHorario _result[] = _dao.findByCurso(cursoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByHorario'
	 * 
	 * @param horarioId
	 */
	public static void findByHorario(long horarioId)
	{
		try {
			CursoHorarioDao _dao = getCursoHorarioDao();
			CursoHorario _result[] = _dao.findByHorario(horarioId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCursoHorarioIdEquals'
	 * 
	 * @param cursoHorarioId
	 */
	public static void findWhereCursoHorarioIdEquals(long cursoHorarioId)
	{
		try {
			CursoHorarioDao _dao = getCursoHorarioDao();
			CursoHorario _result[] = _dao.findWhereCursoHorarioIdEquals(cursoHorarioId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCursoIdEquals'
	 * 
	 * @param cursoId
	 */
	public static void findWhereCursoIdEquals(long cursoId)
	{
		try {
			CursoHorarioDao _dao = getCursoHorarioDao();
			CursoHorario _result[] = _dao.findWhereCursoIdEquals(cursoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHorarioIdEquals'
	 * 
	 * @param horarioId
	 */
	public static void findWhereHorarioIdEquals(long horarioId)
	{
		try {
			CursoHorarioDao _dao = getCursoHorarioDao();
			CursoHorario _result[] = _dao.findWhereHorarioIdEquals(horarioId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCursoHorarioDao'
	 * 
	 * @return CursoHorarioDao
	 */
	public static CursoHorarioDao getCursoHorarioDao()
	{
		return CursoHorarioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(CursoHorario dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getCursoHorarioId() );
		buf.append( ", " );
		buf.append( dto.getCursoId() );
		buf.append( ", " );
		buf.append( dto.getHorarioId() );
		System.out.println( buf.toString() );
	}

}
