/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.CursoDao;
import com.escuela.escuelaOracle.dto.Curso;
import com.escuela.escuelaOracle.exceptions.CursoDaoException;
import com.escuela.escuelaOracle.factory.CursoDaoFactory;

public class CursoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByAsignatura(0);
		// findByProfesor(0);
		// findBySemestre(0);
		// findWhereCursoIdEquals(0);
		// findWhereCupoMaximoEquals(0);
		// findWhereProfesorIdEquals(0);
		// findWhereAsignaturaIdEquals(0);
		// findWhereSemestreIdEquals(0);
		// findWhereClaveGrupoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByAsignatura'
	 * 
	 * @param asignaturaId
	 */
	public static void findByAsignatura(long asignaturaId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findByAsignatura(asignaturaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByProfesor'
	 * 
	 * @param profesorId
	 */
	public static void findByProfesor(long profesorId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findByProfesor(profesorId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findBySemestre'
	 * 
	 * @param semestreId
	 */
	public static void findBySemestre(long semestreId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findBySemestre(semestreId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCursoIdEquals'
	 * 
	 * @param cursoId
	 */
	public static void findWhereCursoIdEquals(long cursoId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findWhereCursoIdEquals(cursoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCupoMaximoEquals'
	 * 
	 * @param cupoMaximo
	 */
	public static void findWhereCupoMaximoEquals(int cupoMaximo)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findWhereCupoMaximoEquals(cupoMaximo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProfesorIdEquals'
	 * 
	 * @param profesorId
	 */
	public static void findWhereProfesorIdEquals(long profesorId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findWhereProfesorIdEquals(profesorId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAsignaturaIdEquals'
	 * 
	 * @param asignaturaId
	 */
	public static void findWhereAsignaturaIdEquals(long asignaturaId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findWhereAsignaturaIdEquals(asignaturaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSemestreIdEquals'
	 * 
	 * @param semestreId
	 */
	public static void findWhereSemestreIdEquals(long semestreId)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findWhereSemestreIdEquals(semestreId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClaveGrupoEquals'
	 * 
	 * @param claveGrupo
	 */
	public static void findWhereClaveGrupoEquals(String claveGrupo)
	{
		try {
			CursoDao _dao = getCursoDao();
			Curso _result[] = _dao.findWhereClaveGrupoEquals(claveGrupo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCursoDao'
	 * 
	 * @return CursoDao
	 */
	public static CursoDao getCursoDao()
	{
		return CursoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Curso dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getCursoId() );
		buf.append( ", " );
		buf.append( dto.getCupoMaximo() );
		buf.append( ", " );
		buf.append( dto.getProfesorId() );
		buf.append( ", " );
		buf.append( dto.getAsignaturaId() );
		buf.append( ", " );
		buf.append( dto.getSemestreId() );
		buf.append( ", " );
		buf.append( dto.getClaveGrupo() );
		System.out.println( buf.toString() );
	}

}
