/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.EstudianteInscritoDao;
import com.escuela.escuelaOracle.dto.EstudianteInscrito;
import com.escuela.escuelaOracle.exceptions.EstudianteInscritoDaoException;
import com.escuela.escuelaOracle.factory.EstudianteInscritoDaoFactory;

public class EstudianteInscritoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByCurso(0);
		// findByEstudiante(0);
		// findWhereEstudianteInscritoIdEquals(0);
		// findWhereCursoIdEquals(0);
		// findWhereEstudianteIdEquals(0);
		// findWhereCalificacionEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCurso'
	 * 
	 * @param cursoId
	 */
	public static void findByCurso(long cursoId)
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findByCurso(cursoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByEstudiante'
	 * 
	 * @param estudianteId
	 */
	public static void findByEstudiante(long estudianteId)
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findByEstudiante(estudianteId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstudianteInscritoIdEquals'
	 * 
	 * @param estudianteInscritoId
	 */
	public static void findWhereEstudianteInscritoIdEquals(long estudianteInscritoId)
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findWhereEstudianteInscritoIdEquals(estudianteInscritoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCursoIdEquals'
	 * 
	 * @param cursoId
	 */
	public static void findWhereCursoIdEquals(long cursoId)
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findWhereCursoIdEquals(cursoId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstudianteIdEquals'
	 * 
	 * @param estudianteId
	 */
	public static void findWhereEstudianteIdEquals(long estudianteId)
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findWhereEstudianteIdEquals(estudianteId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCalificacionEquals'
	 * 
	 * @param calificacion
	 */
	public static void findWhereCalificacionEquals(int calificacion)
	{
		try {
			EstudianteInscritoDao _dao = getEstudianteInscritoDao();
			EstudianteInscrito _result[] = _dao.findWhereCalificacionEquals(calificacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getEstudianteInscritoDao'
	 * 
	 * @return EstudianteInscritoDao
	 */
	public static EstudianteInscritoDao getEstudianteInscritoDao()
	{
		return EstudianteInscritoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(EstudianteInscrito dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getEstudianteInscritoId() );
		buf.append( ", " );
		buf.append( dto.getCursoId() );
		buf.append( ", " );
		buf.append( dto.getEstudianteId() );
		buf.append( ", " );
		buf.append( dto.getCalificacion() );
		System.out.println( buf.toString() );
	}

}
