/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.EstudianteExtraordinarioDao;
import com.escuela.escuelaOracle.dto.EstudianteExtraordinario;
import com.escuela.escuelaOracle.exceptions.EstudianteExtraordinarioDaoException;
import com.escuela.escuelaOracle.factory.EstudianteExtraordinarioDaoFactory;

public class EstudianteExtraordinarioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByAsignatura(0);
		// findWhereEstudianteIdEquals(0);
		// findWhereNumExamenEquals(0);
		// findWhereCalificacionEquals(0);
		// findWhereAsignaturaIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			EstudianteExtraordinarioDao _dao = getEstudianteExtraordinarioDao();
			EstudianteExtraordinario _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByAsignatura'
	 * 
	 * @param asignaturaId
	 */
	public static void findByAsignatura(long asignaturaId)
	{
		try {
			EstudianteExtraordinarioDao _dao = getEstudianteExtraordinarioDao();
			EstudianteExtraordinario _result[] = _dao.findByAsignatura(asignaturaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstudianteIdEquals'
	 * 
	 * @param estudianteId
	 */
	public static void findWhereEstudianteIdEquals(long estudianteId)
	{
		try {
			EstudianteExtraordinarioDao _dao = getEstudianteExtraordinarioDao();
			EstudianteExtraordinario _result[] = _dao.findWhereEstudianteIdEquals(estudianteId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumExamenEquals'
	 * 
	 * @param numExamen
	 */
	public static void findWhereNumExamenEquals(int numExamen)
	{
		try {
			EstudianteExtraordinarioDao _dao = getEstudianteExtraordinarioDao();
			EstudianteExtraordinario _result[] = _dao.findWhereNumExamenEquals(numExamen);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCalificacionEquals'
	 * 
	 * @param calificacion
	 */
	public static void findWhereCalificacionEquals(float calificacion)
	{
		try {
			EstudianteExtraordinarioDao _dao = getEstudianteExtraordinarioDao();
			EstudianteExtraordinario _result[] = _dao.findWhereCalificacionEquals(calificacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAsignaturaIdEquals'
	 * 
	 * @param asignaturaId
	 */
	public static void findWhereAsignaturaIdEquals(long asignaturaId)
	{
		try {
			EstudianteExtraordinarioDao _dao = getEstudianteExtraordinarioDao();
			EstudianteExtraordinario _result[] = _dao.findWhereAsignaturaIdEquals(asignaturaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getEstudianteExtraordinarioDao'
	 * 
	 * @return EstudianteExtraordinarioDao
	 */
	public static EstudianteExtraordinarioDao getEstudianteExtraordinarioDao()
	{
		return EstudianteExtraordinarioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(EstudianteExtraordinario dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getEstudianteId() );
		buf.append( ", " );
		buf.append( dto.getNumExamen() );
		buf.append( ", " );
		buf.append( dto.getCalificacion() );
		buf.append( ", " );
		buf.append( dto.getAsignaturaId() );
		System.out.println( buf.toString() );
	}

}
