/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.EstudianteDao;
import com.escuela.escuelaOracle.dto.Estudiante;
import com.escuela.escuelaOracle.exceptions.EstudianteDaoException;
import com.escuela.escuelaOracle.factory.EstudianteDaoFactory;

public class EstudianteDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByPlanEstudios(0);
		// findWhereEstudianteIdEquals(0);
		// findWhereNombreEquals("");
		// findWhereApellidoPaternoEquals("");
		// findWhereApellidoMaternoEquals("");
		// findWhereFechaNacimientoEquals(null);
		// findWhereFotografiaEquals(null);
		// findWherePlanEstudiosIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByPlanEstudios'
	 * 
	 * @param planEstudiosId
	 */
	public static void findByPlanEstudios(int planEstudiosId)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findByPlanEstudios(planEstudiosId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstudianteIdEquals'
	 * 
	 * @param estudianteId
	 */
	public static void findWhereEstudianteIdEquals(long estudianteId)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWhereEstudianteIdEquals(estudianteId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereApellidoPaternoEquals'
	 * 
	 * @param apellidoPaterno
	 */
	public static void findWhereApellidoPaternoEquals(String apellidoPaterno)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWhereApellidoPaternoEquals(apellidoPaterno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereApellidoMaternoEquals'
	 * 
	 * @param apellidoMaterno
	 */
	public static void findWhereApellidoMaternoEquals(String apellidoMaterno)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWhereApellidoMaternoEquals(apellidoMaterno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaNacimientoEquals'
	 * 
	 * @param fechaNacimiento
	 */
	public static void findWhereFechaNacimientoEquals(Date fechaNacimiento)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWhereFechaNacimientoEquals(fechaNacimiento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFotografiaEquals'
	 * 
	 * @param fotografia
	 */
	public static void findWhereFotografiaEquals(byte[] fotografia)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWhereFotografiaEquals(fotografia);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePlanEstudiosIdEquals'
	 * 
	 * @param planEstudiosId
	 */
	public static void findWherePlanEstudiosIdEquals(int planEstudiosId)
	{
		try {
			EstudianteDao _dao = getEstudianteDao();
			Estudiante _result[] = _dao.findWherePlanEstudiosIdEquals(planEstudiosId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getEstudianteDao'
	 * 
	 * @return EstudianteDao
	 */
	public static EstudianteDao getEstudianteDao()
	{
		return EstudianteDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Estudiante dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getEstudianteId() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getApellidoPaterno() );
		buf.append( ", " );
		buf.append( dto.getApellidoMaterno() );
		buf.append( ", " );
		buf.append( dto.getFechaNacimiento() );
		buf.append( ", " );
		buf.append( dto.getFotografia() );
		buf.append( ", " );
		buf.append( dto.getPlanEstudiosId() );
		System.out.println( buf.toString() );
	}

}
