/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.HorarioDao;
import com.escuela.escuelaOracle.dto.Horario;
import com.escuela.escuelaOracle.exceptions.HorarioDaoException;
import com.escuela.escuelaOracle.factory.HorarioDaoFactory;

public class HorarioDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereHorarioIdEquals(0);
		// findWhereDiaSemanaEquals(0);
		// findWhereHoraInicioEquals(null);
		// findWhereHoraFinEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			HorarioDao _dao = getHorarioDao();
			Horario _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHorarioIdEquals'
	 * 
	 * @param horarioId
	 */
	public static void findWhereHorarioIdEquals(long horarioId)
	{
		try {
			HorarioDao _dao = getHorarioDao();
			Horario _result[] = _dao.findWhereHorarioIdEquals(horarioId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDiaSemanaEquals'
	 * 
	 * @param diaSemana
	 */
	public static void findWhereDiaSemanaEquals(int diaSemana)
	{
		try {
			HorarioDao _dao = getHorarioDao();
			Horario _result[] = _dao.findWhereDiaSemanaEquals(diaSemana);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHoraInicioEquals'
	 * 
	 * @param horaInicio
	 */
	public static void findWhereHoraInicioEquals(Date horaInicio)
	{
		try {
			HorarioDao _dao = getHorarioDao();
			Horario _result[] = _dao.findWhereHoraInicioEquals(horaInicio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHoraFinEquals'
	 * 
	 * @param horaFin
	 */
	public static void findWhereHoraFinEquals(Date horaFin)
	{
		try {
			HorarioDao _dao = getHorarioDao();
			Horario _result[] = _dao.findWhereHoraFinEquals(horaFin);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getHorarioDao'
	 * 
	 * @return HorarioDao
	 */
	public static HorarioDao getHorarioDao()
	{
		return HorarioDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Horario dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getHorarioId() );
		buf.append( ", " );
		buf.append( dto.getDiaSemana() );
		buf.append( ", " );
		buf.append( dto.getHoraInicio() );
		buf.append( ", " );
		buf.append( dto.getHoraFin() );
		System.out.println( buf.toString() );
	}

}
