/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.PlanEstudiosDao;
import com.escuela.escuelaOracle.dto.PlanEstudios;
import com.escuela.escuelaOracle.exceptions.PlanEstudiosDaoException;
import com.escuela.escuelaOracle.factory.PlanEstudiosDaoFactory;

public class PlanEstudiosDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWherePlanEstudiosIdEquals(0);
		// findWhereClaveEquals("");
		// findWhereFechaAprobacionEquals(null);
		// findWhereFechaInicioEquals(null);
		// findWhereFechaFinEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			PlanEstudiosDao _dao = getPlanEstudiosDao();
			PlanEstudios _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePlanEstudiosIdEquals'
	 * 
	 * @param planEstudiosId
	 */
	public static void findWherePlanEstudiosIdEquals(int planEstudiosId)
	{
		try {
			PlanEstudiosDao _dao = getPlanEstudiosDao();
			PlanEstudios _result[] = _dao.findWherePlanEstudiosIdEquals(planEstudiosId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClaveEquals'
	 * 
	 * @param clave
	 */
	public static void findWhereClaveEquals(String clave)
	{
		try {
			PlanEstudiosDao _dao = getPlanEstudiosDao();
			PlanEstudios _result[] = _dao.findWhereClaveEquals(clave);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaAprobacionEquals'
	 * 
	 * @param fechaAprobacion
	 */
	public static void findWhereFechaAprobacionEquals(Date fechaAprobacion)
	{
		try {
			PlanEstudiosDao _dao = getPlanEstudiosDao();
			PlanEstudios _result[] = _dao.findWhereFechaAprobacionEquals(fechaAprobacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaInicioEquals'
	 * 
	 * @param fechaInicio
	 */
	public static void findWhereFechaInicioEquals(Date fechaInicio)
	{
		try {
			PlanEstudiosDao _dao = getPlanEstudiosDao();
			PlanEstudios _result[] = _dao.findWhereFechaInicioEquals(fechaInicio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaFinEquals'
	 * 
	 * @param fechaFin
	 */
	public static void findWhereFechaFinEquals(Date fechaFin)
	{
		try {
			PlanEstudiosDao _dao = getPlanEstudiosDao();
			PlanEstudios _result[] = _dao.findWhereFechaFinEquals(fechaFin);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getPlanEstudiosDao'
	 * 
	 * @return PlanEstudiosDao
	 */
	public static PlanEstudiosDao getPlanEstudiosDao()
	{
		return PlanEstudiosDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(PlanEstudios dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getPlanEstudiosId() );
		buf.append( ", " );
		buf.append( dto.getClave() );
		buf.append( ", " );
		buf.append( dto.getFechaAprobacion() );
		buf.append( ", " );
		buf.append( dto.getFechaInicio() );
		buf.append( ", " );
		buf.append( dto.getFechaFin() );
		System.out.println( buf.toString() );
	}

}
