/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.ProfesorDao;
import com.escuela.escuelaOracle.dto.Profesor;
import com.escuela.escuelaOracle.exceptions.ProfesorDaoException;
import com.escuela.escuelaOracle.factory.ProfesorDaoFactory;

public class ProfesorDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereProfesorIdEquals(0);
		// findWhereNombreEquals("");
		// findWhereApellidoPaternoEquals("");
		// findWhereApellidoMaternoEquals("");
		// findWhereRfcEquals("");
		// findWhereFechaNacimientoEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProfesorIdEquals'
	 * 
	 * @param profesorId
	 */
	public static void findWhereProfesorIdEquals(long profesorId)
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findWhereProfesorIdEquals(profesorId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereApellidoPaternoEquals'
	 * 
	 * @param apellidoPaterno
	 */
	public static void findWhereApellidoPaternoEquals(String apellidoPaterno)
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findWhereApellidoPaternoEquals(apellidoPaterno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereApellidoMaternoEquals'
	 * 
	 * @param apellidoMaterno
	 */
	public static void findWhereApellidoMaternoEquals(String apellidoMaterno)
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findWhereApellidoMaternoEquals(apellidoMaterno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRfcEquals'
	 * 
	 * @param rfc
	 */
	public static void findWhereRfcEquals(String rfc)
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findWhereRfcEquals(rfc);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaNacimientoEquals'
	 * 
	 * @param fechaNacimiento
	 */
	public static void findWhereFechaNacimientoEquals(Date fechaNacimiento)
	{
		try {
			ProfesorDao _dao = getProfesorDao();
			Profesor _result[] = _dao.findWhereFechaNacimientoEquals(fechaNacimiento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProfesorDao'
	 * 
	 * @return ProfesorDao
	 */
	public static ProfesorDao getProfesorDao()
	{
		return ProfesorDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Profesor dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getProfesorId() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getApellidoPaterno() );
		buf.append( ", " );
		buf.append( dto.getApellidoMaterno() );
		buf.append( ", " );
		buf.append( dto.getRfc() );
		buf.append( ", " );
		buf.append( dto.getFechaNacimiento() );
		System.out.println( buf.toString() );
	}

}
