/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.escuela.escuelaOracle.dao.SemestreDao;
import com.escuela.escuelaOracle.dto.Semestre;
import com.escuela.escuelaOracle.exceptions.SemestreDaoException;
import com.escuela.escuelaOracle.factory.SemestreDaoFactory;

public class SemestreDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereSemestreIdEquals(0);
		// findWhereAnioEquals(0);
		// findWherePeriodoEquals(0);
		// findWhereFechaInicioEquals(null);
		// findWhereFechaFinEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			SemestreDao _dao = getSemestreDao();
			Semestre _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSemestreIdEquals'
	 * 
	 * @param semestreId
	 */
	public static void findWhereSemestreIdEquals(long semestreId)
	{
		try {
			SemestreDao _dao = getSemestreDao();
			Semestre _result[] = _dao.findWhereSemestreIdEquals(semestreId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnioEquals'
	 * 
	 * @param anio
	 */
	public static void findWhereAnioEquals(int anio)
	{
		try {
			SemestreDao _dao = getSemestreDao();
			Semestre _result[] = _dao.findWhereAnioEquals(anio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePeriodoEquals'
	 * 
	 * @param periodo
	 */
	public static void findWherePeriodoEquals(int periodo)
	{
		try {
			SemestreDao _dao = getSemestreDao();
			Semestre _result[] = _dao.findWherePeriodoEquals(periodo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaInicioEquals'
	 * 
	 * @param fechaInicio
	 */
	public static void findWhereFechaInicioEquals(Date fechaInicio)
	{
		try {
			SemestreDao _dao = getSemestreDao();
			Semestre _result[] = _dao.findWhereFechaInicioEquals(fechaInicio);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaFinEquals'
	 * 
	 * @param fechaFin
	 */
	public static void findWhereFechaFinEquals(Date fechaFin)
	{
		try {
			SemestreDao _dao = getSemestreDao();
			Semestre _result[] = _dao.findWhereFechaFinEquals(fechaFin);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getSemestreDao'
	 * 
	 * @return SemestreDao
	 */
	public static SemestreDao getSemestreDao()
	{
		return SemestreDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Semestre dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getSemestreId() );
		buf.append( ", " );
		buf.append( dto.getAnio() );
		buf.append( ", " );
		buf.append( dto.getPeriodo() );
		buf.append( ", " );
		buf.append( dto.getFechaInicio() );
		buf.append( ", " );
		buf.append( dto.getFechaFin() );
		System.out.println( buf.toString() );
	}

}
