/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class AsignaturaDaoImpl extends AbstractDAO implements AsignaturaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ASIGNATURA_ID, NOMBRE, CREDITOS, ASIGNATURA_REQUERIDA_ID, PLAN_ESTUDIOS_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ASIGNATURA_ID, NOMBRE, CREDITOS, ASIGNATURA_REQUERIDA_ID, PLAN_ESTUDIOS_ID ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ASIGNATURA_ID = ?, NOMBRE = ?, CREDITOS = ?, ASIGNATURA_REQUERIDA_ID = ?, PLAN_ESTUDIOS_ID = ? WHERE ASIGNATURA_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ASIGNATURA_ID = ?";

	/** 
	 * Index of column ASIGNATURA_ID
	 */
	protected static final int COLUMN_ASIGNATURA_ID = 1;

	/** 
	 * Index of column NOMBRE
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column CREDITOS
	 */
	protected static final int COLUMN_CREDITOS = 3;

	/** 
	 * Index of column ASIGNATURA_REQUERIDA_ID
	 */
	protected static final int COLUMN_ASIGNATURA_REQUERIDA_ID = 4;

	/** 
	 * Index of column PLAN_ESTUDIOS_ID
	 */
	protected static final int COLUMN_PLAN_ESTUDIOS_ID = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column ASIGNATURA_ID
	 */
	protected static final int PK_COLUMN_ASIGNATURA_ID = 1;

	/** 
	 * Inserts a new row in the ASIGNATURA table.
	 */
	public AsignaturaPk insert(Asignatura dto) throws AsignaturaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getAsignaturaId() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setInt( index++, dto.getCreditos() );
			if (dto.isAsignaturaRequeridaIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getAsignaturaRequeridaId() );
			}
		
			stmt.setInt( index++, dto.getPlanEstudiosId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AsignaturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ASIGNATURA table.
	 */
	public void update(AsignaturaPk pk, Asignatura dto) throws AsignaturaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getAsignaturaId() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setInt( index++, dto.getCreditos() );
			if (dto.isAsignaturaRequeridaIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getAsignaturaRequeridaId() );
			}
		
			stmt.setInt( index++, dto.getPlanEstudiosId() );
			stmt.setLong( 6, pk.getAsignaturaId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AsignaturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ASIGNATURA table.
	 */
	public void delete(AsignaturaPk pk) throws AsignaturaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getAsignaturaId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AsignaturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ASIGNATURA table that matches the specified primary-key value.
	 */
	public Asignatura findByPrimaryKey(AsignaturaPk pk) throws AsignaturaDaoException
	{
		return findByPrimaryKey( pk.getAsignaturaId() );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Asignatura findByPrimaryKey(long asignaturaId) throws AsignaturaDaoException
	{
		Asignatura ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_ID = ?", new Object[] {  new Long(asignaturaId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria ''.
	 */
	public Asignatura[] findAll() throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ASIGNATURA_ID", null );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_REQUERIDA_ID = :asignaturaRequeridaId'.
	 */
	public Asignatura[] findByAsignatura(long asignaturaRequeridaId) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_REQUERIDA_ID = ?", new Object[] {  new Long(asignaturaRequeridaId) } );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Asignatura[] findByPlanEstudios(int planEstudiosId) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PLAN_ESTUDIOS_ID = ?", new Object[] {  new Integer(planEstudiosId) } );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Asignatura[] findWhereAsignaturaIdEquals(long asignaturaId) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_ID = ? ORDER BY ASIGNATURA_ID", new Object[] {  new Long(asignaturaId) } );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Asignatura[] findWhereNombreEquals(String nombre) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE = ? ORDER BY NOMBRE", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'CREDITOS = :creditos'.
	 */
	public Asignatura[] findWhereCreditosEquals(int creditos) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CREDITOS = ? ORDER BY CREDITOS", new Object[] {  new Integer(creditos) } );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'ASIGNATURA_REQUERIDA_ID = :asignaturaRequeridaId'.
	 */
	public Asignatura[] findWhereAsignaturaRequeridaIdEquals(long asignaturaRequeridaId) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_REQUERIDA_ID = ? ORDER BY ASIGNATURA_REQUERIDA_ID", new Object[] {  new Long(asignaturaRequeridaId) } );
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Asignatura[] findWherePlanEstudiosIdEquals(int planEstudiosId) throws AsignaturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PLAN_ESTUDIOS_ID = ? ORDER BY PLAN_ESTUDIOS_ID", new Object[] {  new Integer(planEstudiosId) } );
	}

	/**
	 * Method 'AsignaturaDaoImpl'
	 * 
	 */
	public AsignaturaDaoImpl()
	{
	}

	/**
	 * Method 'AsignaturaDaoImpl'
	 * 
	 * @param userConn
	 */
	public AsignaturaDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.ASIGNATURA";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Asignatura fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Asignatura dto = new Asignatura();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Asignatura[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Asignatura dto = new Asignatura();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Asignatura ret[] = new Asignatura[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Asignatura dto, ResultSet rs) throws SQLException
	{
		dto.setAsignaturaId( rs.getLong( COLUMN_ASIGNATURA_ID ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setCreditos( rs.getInt( COLUMN_CREDITOS ) );
		dto.setAsignaturaRequeridaId( rs.getLong( COLUMN_ASIGNATURA_REQUERIDA_ID ) );
		if (rs.wasNull()) {
			dto.setAsignaturaRequeridaIdNull( true );
		}
		
		dto.setPlanEstudiosId( rs.getInt( COLUMN_PLAN_ESTUDIOS_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Asignatura dto)
	{
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the specified arbitrary SQL statement
	 */
	public Asignatura[] findByDynamicSelect(String sql, Object[] sqlParams) throws AsignaturaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AsignaturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ASIGNATURA table that match the specified arbitrary SQL statement
	 */
	public Asignatura[] findByDynamicWhere(String sql, Object[] sqlParams) throws AsignaturaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AsignaturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
