/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CursoHorarioDaoImpl extends AbstractDAO implements CursoHorarioDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT CURSO_HORARIO_ID, CURSO_ID, HORARIO_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( CURSO_HORARIO_ID, CURSO_ID, HORARIO_ID ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET CURSO_HORARIO_ID = ?, CURSO_ID = ?, HORARIO_ID = ? WHERE CURSO_HORARIO_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE CURSO_HORARIO_ID = ?";

	/** 
	 * Index of column CURSO_HORARIO_ID
	 */
	protected static final int COLUMN_CURSO_HORARIO_ID = 1;

	/** 
	 * Index of column CURSO_ID
	 */
	protected static final int COLUMN_CURSO_ID = 2;

	/** 
	 * Index of column HORARIO_ID
	 */
	protected static final int COLUMN_HORARIO_ID = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column CURSO_HORARIO_ID
	 */
	protected static final int PK_COLUMN_CURSO_HORARIO_ID = 1;

	/** 
	 * Inserts a new row in the CURSO_HORARIO table.
	 */
	public CursoHorarioPk insert(CursoHorario dto) throws CursoHorarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getCursoHorarioId() );
			stmt.setLong( index++, dto.getCursoId() );
			stmt.setLong( index++, dto.getHorarioId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoHorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the CURSO_HORARIO table.
	 */
	public void update(CursoHorarioPk pk, CursoHorario dto) throws CursoHorarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getCursoHorarioId() );
			stmt.setLong( index++, dto.getCursoId() );
			stmt.setLong( index++, dto.getHorarioId() );
			stmt.setLong( 4, pk.getCursoHorarioId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoHorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the CURSO_HORARIO table.
	 */
	public void delete(CursoHorarioPk pk) throws CursoHorarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getCursoHorarioId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoHorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the CURSO_HORARIO table that matches the specified primary-key value.
	 */
	public CursoHorario findByPrimaryKey(CursoHorarioPk pk) throws CursoHorarioDaoException
	{
		return findByPrimaryKey( pk.getCursoHorarioId() );
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_HORARIO_ID = :cursoHorarioId'.
	 */
	public CursoHorario findByPrimaryKey(long cursoHorarioId) throws CursoHorarioDaoException
	{
		CursoHorario ret[] = findByDynamicSelect( SQL_SELECT + " WHERE CURSO_HORARIO_ID = ?", new Object[] {  new Long(cursoHorarioId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria ''.
	 */
	public CursoHorario[] findAll() throws CursoHorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY CURSO_HORARIO_ID", null );
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public CursoHorario[] findByCurso(long cursoId) throws CursoHorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CURSO_ID = ?", new Object[] {  new Long(cursoId) } );
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public CursoHorario[] findByHorario(long horarioId) throws CursoHorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HORARIO_ID = ?", new Object[] {  new Long(horarioId) } );
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_HORARIO_ID = :cursoHorarioId'.
	 */
	public CursoHorario[] findWhereCursoHorarioIdEquals(long cursoHorarioId) throws CursoHorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CURSO_HORARIO_ID = ? ORDER BY CURSO_HORARIO_ID", new Object[] {  new Long(cursoHorarioId) } );
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public CursoHorario[] findWhereCursoIdEquals(long cursoId) throws CursoHorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CURSO_ID = ? ORDER BY CURSO_ID", new Object[] {  new Long(cursoId) } );
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public CursoHorario[] findWhereHorarioIdEquals(long horarioId) throws CursoHorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HORARIO_ID = ? ORDER BY HORARIO_ID", new Object[] {  new Long(horarioId) } );
	}

	/**
	 * Method 'CursoHorarioDaoImpl'
	 * 
	 */
	public CursoHorarioDaoImpl()
	{
	}

	/**
	 * Method 'CursoHorarioDaoImpl'
	 * 
	 * @param userConn
	 */
	public CursoHorarioDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.CURSO_HORARIO";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected CursoHorario fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			CursoHorario dto = new CursoHorario();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected CursoHorario[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			CursoHorario dto = new CursoHorario();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		CursoHorario ret[] = new CursoHorario[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(CursoHorario dto, ResultSet rs) throws SQLException
	{
		dto.setCursoHorarioId( rs.getLong( COLUMN_CURSO_HORARIO_ID ) );
		dto.setCursoId( rs.getLong( COLUMN_CURSO_ID ) );
		dto.setHorarioId( rs.getLong( COLUMN_HORARIO_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(CursoHorario dto)
	{
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the specified arbitrary SQL statement
	 */
	public CursoHorario[] findByDynamicSelect(String sql, Object[] sqlParams) throws CursoHorarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoHorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the CURSO_HORARIO table that match the specified arbitrary SQL statement
	 */
	public CursoHorario[] findByDynamicWhere(String sql, Object[] sqlParams) throws CursoHorarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoHorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
