/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CursoDaoImpl extends AbstractDAO implements CursoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT CURSO_ID, CUPO_MAXIMO, PROFESOR_ID, ASIGNATURA_ID, SEMESTRE_ID, CLAVE_GRUPO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( CURSO_ID, CUPO_MAXIMO, PROFESOR_ID, ASIGNATURA_ID, SEMESTRE_ID, CLAVE_GRUPO ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET CURSO_ID = ?, CUPO_MAXIMO = ?, PROFESOR_ID = ?, ASIGNATURA_ID = ?, SEMESTRE_ID = ?, CLAVE_GRUPO = ? WHERE CURSO_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE CURSO_ID = ?";

	/** 
	 * Index of column CURSO_ID
	 */
	protected static final int COLUMN_CURSO_ID = 1;

	/** 
	 * Index of column CUPO_MAXIMO
	 */
	protected static final int COLUMN_CUPO_MAXIMO = 2;

	/** 
	 * Index of column PROFESOR_ID
	 */
	protected static final int COLUMN_PROFESOR_ID = 3;

	/** 
	 * Index of column ASIGNATURA_ID
	 */
	protected static final int COLUMN_ASIGNATURA_ID = 4;

	/** 
	 * Index of column SEMESTRE_ID
	 */
	protected static final int COLUMN_SEMESTRE_ID = 5;

	/** 
	 * Index of column CLAVE_GRUPO
	 */
	protected static final int COLUMN_CLAVE_GRUPO = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column CURSO_ID
	 */
	protected static final int PK_COLUMN_CURSO_ID = 1;

	/** 
	 * Inserts a new row in the CURSO table.
	 */
	public CursoPk insert(Curso dto) throws CursoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getCursoId() );
			stmt.setInt( index++, dto.getCupoMaximo() );
			stmt.setLong( index++, dto.getProfesorId() );
			stmt.setLong( index++, dto.getAsignaturaId() );
			stmt.setLong( index++, dto.getSemestreId() );
			stmt.setString( index++, dto.getClaveGrupo() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the CURSO table.
	 */
	public void update(CursoPk pk, Curso dto) throws CursoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getCursoId() );
			stmt.setInt( index++, dto.getCupoMaximo() );
			stmt.setLong( index++, dto.getProfesorId() );
			stmt.setLong( index++, dto.getAsignaturaId() );
			stmt.setLong( index++, dto.getSemestreId() );
			stmt.setString( index++, dto.getClaveGrupo() );
			stmt.setLong( 7, pk.getCursoId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the CURSO table.
	 */
	public void delete(CursoPk pk) throws CursoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getCursoId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the CURSO table that matches the specified primary-key value.
	 */
	public Curso findByPrimaryKey(CursoPk pk) throws CursoDaoException
	{
		return findByPrimaryKey( pk.getCursoId() );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public Curso findByPrimaryKey(long cursoId) throws CursoDaoException
	{
		Curso ret[] = findByDynamicSelect( SQL_SELECT + " WHERE CURSO_ID = ?", new Object[] {  new Long(cursoId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria ''.
	 */
	public Curso[] findAll() throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY CURSO_ID", null );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Curso[] findByAsignatura(long asignaturaId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_ID = ?", new Object[] {  new Long(asignaturaId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Curso[] findByProfesor(long profesorId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROFESOR_ID = ?", new Object[] {  new Long(profesorId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Curso[] findBySemestre(long semestreId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SEMESTRE_ID = ?", new Object[] {  new Long(semestreId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public Curso[] findWhereCursoIdEquals(long cursoId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CURSO_ID = ? ORDER BY CURSO_ID", new Object[] {  new Long(cursoId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CUPO_MAXIMO = :cupoMaximo'.
	 */
	public Curso[] findWhereCupoMaximoEquals(int cupoMaximo) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CUPO_MAXIMO = ? ORDER BY CUPO_MAXIMO", new Object[] {  new Integer(cupoMaximo) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Curso[] findWhereProfesorIdEquals(long profesorId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROFESOR_ID = ? ORDER BY PROFESOR_ID", new Object[] {  new Long(profesorId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public Curso[] findWhereAsignaturaIdEquals(long asignaturaId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_ID = ? ORDER BY ASIGNATURA_ID", new Object[] {  new Long(asignaturaId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Curso[] findWhereSemestreIdEquals(long semestreId) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SEMESTRE_ID = ? ORDER BY SEMESTRE_ID", new Object[] {  new Long(semestreId) } );
	}

	/** 
	 * Returns all rows from the CURSO table that match the criteria 'CLAVE_GRUPO = :claveGrupo'.
	 */
	public Curso[] findWhereClaveGrupoEquals(String claveGrupo) throws CursoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CLAVE_GRUPO = ? ORDER BY CLAVE_GRUPO", new Object[] { claveGrupo } );
	}

	/**
	 * Method 'CursoDaoImpl'
	 * 
	 */
	public CursoDaoImpl()
	{
	}

	/**
	 * Method 'CursoDaoImpl'
	 * 
	 * @param userConn
	 */
	public CursoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.CURSO";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Curso fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Curso dto = new Curso();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Curso[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Curso dto = new Curso();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Curso ret[] = new Curso[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Curso dto, ResultSet rs) throws SQLException
	{
		dto.setCursoId( rs.getLong( COLUMN_CURSO_ID ) );
		dto.setCupoMaximo( rs.getInt( COLUMN_CUPO_MAXIMO ) );
		dto.setProfesorId( rs.getLong( COLUMN_PROFESOR_ID ) );
		dto.setAsignaturaId( rs.getLong( COLUMN_ASIGNATURA_ID ) );
		dto.setSemestreId( rs.getLong( COLUMN_SEMESTRE_ID ) );
		dto.setClaveGrupo( rs.getString( COLUMN_CLAVE_GRUPO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Curso dto)
	{
	}

	/** 
	 * Returns all rows from the CURSO table that match the specified arbitrary SQL statement
	 */
	public Curso[] findByDynamicSelect(String sql, Object[] sqlParams) throws CursoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the CURSO table that match the specified arbitrary SQL statement
	 */
	public Curso[] findByDynamicWhere(String sql, Object[] sqlParams) throws CursoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CursoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
