/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EstudianteDaoImpl extends AbstractDAO implements EstudianteDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ESTUDIANTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, FOTOGRAFIA, PLAN_ESTUDIOS_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ESTUDIANTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, FOTOGRAFIA, PLAN_ESTUDIOS_ID ) VALUES ( ?, ?, ?, ?, ?, EMPTY_BLOB(), ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ESTUDIANTE_ID = ?, NOMBRE = ?, APELLIDO_PATERNO = ?, APELLIDO_MATERNO = ?, FECHA_NACIMIENTO = ?, FOTOGRAFIA = EMPTY_BLOB(), PLAN_ESTUDIOS_ID = ? WHERE ESTUDIANTE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ESTUDIANTE_ID = ?";

	/** 
	 * Index of column ESTUDIANTE_ID
	 */
	protected static final int COLUMN_ESTUDIANTE_ID = 1;

	/** 
	 * Index of column NOMBRE
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column APELLIDO_PATERNO
	 */
	protected static final int COLUMN_APELLIDO_PATERNO = 3;

	/** 
	 * Index of column APELLIDO_MATERNO
	 */
	protected static final int COLUMN_APELLIDO_MATERNO = 4;

	/** 
	 * Index of column FECHA_NACIMIENTO
	 */
	protected static final int COLUMN_FECHA_NACIMIENTO = 5;

	/** 
	 * Index of column FOTOGRAFIA
	 */
	protected static final int COLUMN_FOTOGRAFIA = 6;

	/** 
	 * Index of column PLAN_ESTUDIOS_ID
	 */
	protected static final int COLUMN_PLAN_ESTUDIOS_ID = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column ESTUDIANTE_ID
	 */
	protected static final int PK_COLUMN_ESTUDIANTE_ID = 1;

	/** 
	 * Inserts a new row in the ESTUDIANTE table.
	 */
	public EstudiantePk insert(Estudiante dto) throws EstudianteDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getEstudianteId() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getApellidoPaterno() );
			stmt.setString( index++, dto.getApellidoMaterno() );
			stmt.setTimestamp(index++, dto.getFechaNacimiento()==null ? null : new java.sql.Timestamp( dto.getFechaNacimiento().getTime() ) );
			// no need to bind value for LOB column
			if (dto.isPlanEstudiosIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getPlanEstudiosId() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ESTUDIANTE table.
	 */
	public void update(EstudiantePk pk, Estudiante dto) throws EstudianteDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getEstudianteId() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getApellidoPaterno() );
			stmt.setString( index++, dto.getApellidoMaterno() );
			stmt.setTimestamp(index++, dto.getFechaNacimiento()==null ? null : new java.sql.Timestamp( dto.getFechaNacimiento().getTime() ) );
			// no need to bind value for LOB column
			if (dto.isPlanEstudiosIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getPlanEstudiosId() );
			}
		
			stmt.setLong( 7, pk.getEstudianteId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ESTUDIANTE table.
	 */
	public void delete(EstudiantePk pk) throws EstudianteDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getEstudianteId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ESTUDIANTE table that matches the specified primary-key value.
	 */
	public Estudiante findByPrimaryKey(EstudiantePk pk) throws EstudianteDaoException
	{
		return findByPrimaryKey( pk.getEstudianteId() );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public Estudiante findByPrimaryKey(long estudianteId) throws EstudianteDaoException
	{
		Estudiante ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_ID = ?", new Object[] {  new Long(estudianteId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria ''.
	 */
	public Estudiante[] findAll() throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ESTUDIANTE_ID", null );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Estudiante[] findByPlanEstudios(int planEstudiosId) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PLAN_ESTUDIOS_ID = ?", new Object[] {  new Integer(planEstudiosId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public Estudiante[] findWhereEstudianteIdEquals(long estudianteId) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_ID = ? ORDER BY ESTUDIANTE_ID", new Object[] {  new Long(estudianteId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Estudiante[] findWhereNombreEquals(String nombre) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE = ? ORDER BY NOMBRE", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'APELLIDO_PATERNO = :apellidoPaterno'.
	 */
	public Estudiante[] findWhereApellidoPaternoEquals(String apellidoPaterno) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE APELLIDO_PATERNO = ? ORDER BY APELLIDO_PATERNO", new Object[] { apellidoPaterno } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'APELLIDO_MATERNO = :apellidoMaterno'.
	 */
	public Estudiante[] findWhereApellidoMaternoEquals(String apellidoMaterno) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE APELLIDO_MATERNO = ? ORDER BY APELLIDO_MATERNO", new Object[] { apellidoMaterno } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'FECHA_NACIMIENTO = :fechaNacimiento'.
	 */
	public Estudiante[] findWhereFechaNacimientoEquals(Date fechaNacimiento) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_NACIMIENTO = ? ORDER BY FECHA_NACIMIENTO", new Object[] { fechaNacimiento==null ? null : new java.sql.Timestamp( fechaNacimiento.getTime() ) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'FOTOGRAFIA = :fotografia'.
	 */
	public Estudiante[] findWhereFotografiaEquals(byte[] fotografia) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FOTOGRAFIA = ? ORDER BY FOTOGRAFIA", new Object[] { fotografia } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public Estudiante[] findWherePlanEstudiosIdEquals(int planEstudiosId) throws EstudianteDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PLAN_ESTUDIOS_ID = ? ORDER BY PLAN_ESTUDIOS_ID", new Object[] {  new Integer(planEstudiosId) } );
	}

	/**
	 * Method 'EstudianteDaoImpl'
	 * 
	 */
	public EstudianteDaoImpl()
	{
	}

	/**
	 * Method 'EstudianteDaoImpl'
	 * 
	 * @param userConn
	 */
	public EstudianteDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.ESTUDIANTE";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Estudiante fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Estudiante dto = new Estudiante();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Estudiante[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Estudiante dto = new Estudiante();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Estudiante ret[] = new Estudiante[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Estudiante dto, ResultSet rs) throws SQLException
	{
		dto.setEstudianteId( rs.getLong( COLUMN_ESTUDIANTE_ID ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setApellidoPaterno( rs.getString( COLUMN_APELLIDO_PATERNO ) );
		dto.setApellidoMaterno( rs.getString( COLUMN_APELLIDO_MATERNO ) );
		dto.setFechaNacimiento( rs.getTimestamp(COLUMN_FECHA_NACIMIENTO ) );
		dto.setFotografia( super.getBlobColumn(rs, COLUMN_FOTOGRAFIA ) );
		dto.setPlanEstudiosId( rs.getInt( COLUMN_PLAN_ESTUDIOS_ID ) );
		if (rs.wasNull()) {
			dto.setPlanEstudiosIdNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Estudiante dto)
	{
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the specified arbitrary SQL statement
	 */
	public Estudiante[] findByDynamicSelect(String sql, Object[] sqlParams) throws EstudianteDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ESTUDIANTE table that match the specified arbitrary SQL statement
	 */
	public Estudiante[] findByDynamicWhere(String sql, Object[] sqlParams) throws EstudianteDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
