/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EstudianteExtraordinarioDaoImpl extends AbstractDAO implements EstudianteExtraordinarioDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ESTUDIANTE_ID, NUM_EXAMEN, CALIFICACION, ASIGNATURA_ID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ESTUDIANTE_ID, NUM_EXAMEN, CALIFICACION, ASIGNATURA_ID ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ESTUDIANTE_ID = ?, NUM_EXAMEN = ?, CALIFICACION = ?, ASIGNATURA_ID = ? WHERE ESTUDIANTE_ID = ? AND NUM_EXAMEN = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ESTUDIANTE_ID = ? AND NUM_EXAMEN = ?";

	/** 
	 * Index of column ESTUDIANTE_ID
	 */
	protected static final int COLUMN_ESTUDIANTE_ID = 1;

	/** 
	 * Index of column NUM_EXAMEN
	 */
	protected static final int COLUMN_NUM_EXAMEN = 2;

	/** 
	 * Index of column CALIFICACION
	 */
	protected static final int COLUMN_CALIFICACION = 3;

	/** 
	 * Index of column ASIGNATURA_ID
	 */
	protected static final int COLUMN_ASIGNATURA_ID = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ESTUDIANTE_ID
	 */
	protected static final int PK_COLUMN_ESTUDIANTE_ID = 1;

	/** 
	 * Index of primary-key column NUM_EXAMEN
	 */
	protected static final int PK_COLUMN_NUM_EXAMEN = 2;

	/** 
	 * Inserts a new row in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	public EstudianteExtraordinarioPk insert(EstudianteExtraordinario dto) throws EstudianteExtraordinarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getEstudianteId() );
			stmt.setInt( index++, dto.getNumExamen() );
			stmt.setFloat( index++, dto.getCalificacion() );
			stmt.setLong( index++, dto.getAsignaturaId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteExtraordinarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	public void update(EstudianteExtraordinarioPk pk, EstudianteExtraordinario dto) throws EstudianteExtraordinarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getEstudianteId() );
			stmt.setInt( index++, dto.getNumExamen() );
			stmt.setFloat( index++, dto.getCalificacion() );
			stmt.setLong( index++, dto.getAsignaturaId() );
			stmt.setLong( 5, pk.getEstudianteId() );
			stmt.setInt( 6, pk.getNumExamen() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteExtraordinarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ESTUDIANTE_EXTRAORDINARIO table.
	 */
	public void delete(EstudianteExtraordinarioPk pk) throws EstudianteExtraordinarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getEstudianteId() );
			stmt.setInt( 2, pk.getNumExamen() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteExtraordinarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ESTUDIANTE_EXTRAORDINARIO table that matches the specified primary-key value.
	 */
	public EstudianteExtraordinario findByPrimaryKey(EstudianteExtraordinarioPk pk) throws EstudianteExtraordinarioDaoException
	{
		return findByPrimaryKey( pk.getEstudianteId(), pk.getNumExamen() );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ESTUDIANTE_ID = :estudianteId AND NUM_EXAMEN = :numExamen'.
	 */
	public EstudianteExtraordinario findByPrimaryKey(long estudianteId, int numExamen) throws EstudianteExtraordinarioDaoException
	{
		EstudianteExtraordinario ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_ID = ? AND NUM_EXAMEN = ?", new Object[] {  new Long(estudianteId),  new Integer(numExamen) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria ''.
	 */
	public EstudianteExtraordinario[] findAll() throws EstudianteExtraordinarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ESTUDIANTE_ID, NUM_EXAMEN", null );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public EstudianteExtraordinario[] findByAsignatura(long asignaturaId) throws EstudianteExtraordinarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_ID = ?", new Object[] {  new Long(asignaturaId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public EstudianteExtraordinario[] findWhereEstudianteIdEquals(long estudianteId) throws EstudianteExtraordinarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_ID = ? ORDER BY ESTUDIANTE_ID", new Object[] {  new Long(estudianteId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'NUM_EXAMEN = :numExamen'.
	 */
	public EstudianteExtraordinario[] findWhereNumExamenEquals(int numExamen) throws EstudianteExtraordinarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NUM_EXAMEN = ? ORDER BY NUM_EXAMEN", new Object[] {  new Integer(numExamen) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'CALIFICACION = :calificacion'.
	 */
	public EstudianteExtraordinario[] findWhereCalificacionEquals(float calificacion) throws EstudianteExtraordinarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CALIFICACION = ? ORDER BY CALIFICACION", new Object[] {  new Float(calificacion) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the criteria 'ASIGNATURA_ID = :asignaturaId'.
	 */
	public EstudianteExtraordinario[] findWhereAsignaturaIdEquals(long asignaturaId) throws EstudianteExtraordinarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASIGNATURA_ID = ? ORDER BY ASIGNATURA_ID", new Object[] {  new Long(asignaturaId) } );
	}

	/**
	 * Method 'EstudianteExtraordinarioDaoImpl'
	 * 
	 */
	public EstudianteExtraordinarioDaoImpl()
	{
	}

	/**
	 * Method 'EstudianteExtraordinarioDaoImpl'
	 * 
	 * @param userConn
	 */
	public EstudianteExtraordinarioDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.ESTUDIANTE_EXTRAORDINARIO";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EstudianteExtraordinario fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EstudianteExtraordinario dto = new EstudianteExtraordinario();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EstudianteExtraordinario[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EstudianteExtraordinario dto = new EstudianteExtraordinario();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EstudianteExtraordinario ret[] = new EstudianteExtraordinario[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EstudianteExtraordinario dto, ResultSet rs) throws SQLException
	{
		dto.setEstudianteId( rs.getLong( COLUMN_ESTUDIANTE_ID ) );
		dto.setNumExamen( rs.getInt( COLUMN_NUM_EXAMEN ) );
		dto.setCalificacion( rs.getFloat( COLUMN_CALIFICACION ) );
		dto.setAsignaturaId( rs.getLong( COLUMN_ASIGNATURA_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EstudianteExtraordinario dto)
	{
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the specified arbitrary SQL statement
	 */
	public EstudianteExtraordinario[] findByDynamicSelect(String sql, Object[] sqlParams) throws EstudianteExtraordinarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteExtraordinarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_EXTRAORDINARIO table that match the specified arbitrary SQL statement
	 */
	public EstudianteExtraordinario[] findByDynamicWhere(String sql, Object[] sqlParams) throws EstudianteExtraordinarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteExtraordinarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
