/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EstudianteInscritoDaoImpl extends AbstractDAO implements EstudianteInscritoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ESTUDIANTE_INSCRITO_ID, CURSO_ID, ESTUDIANTE_ID, CALIFICACION FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ESTUDIANTE_INSCRITO_ID, CURSO_ID, ESTUDIANTE_ID, CALIFICACION ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ESTUDIANTE_INSCRITO_ID = ?, CURSO_ID = ?, ESTUDIANTE_ID = ?, CALIFICACION = ? WHERE ESTUDIANTE_INSCRITO_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ESTUDIANTE_INSCRITO_ID = ?";

	/** 
	 * Index of column ESTUDIANTE_INSCRITO_ID
	 */
	protected static final int COLUMN_ESTUDIANTE_INSCRITO_ID = 1;

	/** 
	 * Index of column CURSO_ID
	 */
	protected static final int COLUMN_CURSO_ID = 2;

	/** 
	 * Index of column ESTUDIANTE_ID
	 */
	protected static final int COLUMN_ESTUDIANTE_ID = 3;

	/** 
	 * Index of column CALIFICACION
	 */
	protected static final int COLUMN_CALIFICACION = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ESTUDIANTE_INSCRITO_ID
	 */
	protected static final int PK_COLUMN_ESTUDIANTE_INSCRITO_ID = 1;

	/** 
	 * Inserts a new row in the ESTUDIANTE_INSCRITO table.
	 */
	public EstudianteInscritoPk insert(EstudianteInscrito dto) throws EstudianteInscritoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getEstudianteInscritoId() );
			if (dto.isCursoIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getCursoId() );
			}
		
			if (dto.isEstudianteIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getEstudianteId() );
			}
		
			if (dto.isCalificacionNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getCalificacion() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteInscritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ESTUDIANTE_INSCRITO table.
	 */
	public void update(EstudianteInscritoPk pk, EstudianteInscrito dto) throws EstudianteInscritoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getEstudianteInscritoId() );
			if (dto.isCursoIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getCursoId() );
			}
		
			if (dto.isEstudianteIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getEstudianteId() );
			}
		
			if (dto.isCalificacionNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getCalificacion() );
			}
		
			stmt.setLong( 5, pk.getEstudianteInscritoId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteInscritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ESTUDIANTE_INSCRITO table.
	 */
	public void delete(EstudianteInscritoPk pk) throws EstudianteInscritoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getEstudianteInscritoId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteInscritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ESTUDIANTE_INSCRITO table that matches the specified primary-key value.
	 */
	public EstudianteInscrito findByPrimaryKey(EstudianteInscritoPk pk) throws EstudianteInscritoDaoException
	{
		return findByPrimaryKey( pk.getEstudianteInscritoId() );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_INSCRITO_ID = :estudianteInscritoId'.
	 */
	public EstudianteInscrito findByPrimaryKey(long estudianteInscritoId) throws EstudianteInscritoDaoException
	{
		EstudianteInscrito ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_INSCRITO_ID = ?", new Object[] {  new Long(estudianteInscritoId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria ''.
	 */
	public EstudianteInscrito[] findAll() throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ESTUDIANTE_INSCRITO_ID", null );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public EstudianteInscrito[] findByCurso(long cursoId) throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CURSO_ID = ?", new Object[] {  new Long(cursoId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public EstudianteInscrito[] findByEstudiante(long estudianteId) throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_ID = ?", new Object[] {  new Long(estudianteId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_INSCRITO_ID = :estudianteInscritoId'.
	 */
	public EstudianteInscrito[] findWhereEstudianteInscritoIdEquals(long estudianteInscritoId) throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_INSCRITO_ID = ? ORDER BY ESTUDIANTE_INSCRITO_ID", new Object[] {  new Long(estudianteInscritoId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'CURSO_ID = :cursoId'.
	 */
	public EstudianteInscrito[] findWhereCursoIdEquals(long cursoId) throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CURSO_ID = ? ORDER BY CURSO_ID", new Object[] {  new Long(cursoId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'ESTUDIANTE_ID = :estudianteId'.
	 */
	public EstudianteInscrito[] findWhereEstudianteIdEquals(long estudianteId) throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTUDIANTE_ID = ? ORDER BY ESTUDIANTE_ID", new Object[] {  new Long(estudianteId) } );
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the criteria 'CALIFICACION = :calificacion'.
	 */
	public EstudianteInscrito[] findWhereCalificacionEquals(int calificacion) throws EstudianteInscritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CALIFICACION = ? ORDER BY CALIFICACION", new Object[] {  new Integer(calificacion) } );
	}

	/**
	 * Method 'EstudianteInscritoDaoImpl'
	 * 
	 */
	public EstudianteInscritoDaoImpl()
	{
	}

	/**
	 * Method 'EstudianteInscritoDaoImpl'
	 * 
	 * @param userConn
	 */
	public EstudianteInscritoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.ESTUDIANTE_INSCRITO";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EstudianteInscrito fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EstudianteInscrito dto = new EstudianteInscrito();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EstudianteInscrito[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EstudianteInscrito dto = new EstudianteInscrito();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EstudianteInscrito ret[] = new EstudianteInscrito[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EstudianteInscrito dto, ResultSet rs) throws SQLException
	{
		dto.setEstudianteInscritoId( rs.getLong( COLUMN_ESTUDIANTE_INSCRITO_ID ) );
		dto.setCursoId( rs.getLong( COLUMN_CURSO_ID ) );
		if (rs.wasNull()) {
			dto.setCursoIdNull( true );
		}
		
		dto.setEstudianteId( rs.getLong( COLUMN_ESTUDIANTE_ID ) );
		if (rs.wasNull()) {
			dto.setEstudianteIdNull( true );
		}
		
		dto.setCalificacion( rs.getInt( COLUMN_CALIFICACION ) );
		if (rs.wasNull()) {
			dto.setCalificacionNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EstudianteInscrito dto)
	{
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the specified arbitrary SQL statement
	 */
	public EstudianteInscrito[] findByDynamicSelect(String sql, Object[] sqlParams) throws EstudianteInscritoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteInscritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ESTUDIANTE_INSCRITO table that match the specified arbitrary SQL statement
	 */
	public EstudianteInscrito[] findByDynamicWhere(String sql, Object[] sqlParams) throws EstudianteInscritoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EstudianteInscritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
