/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class HorarioDaoImpl extends AbstractDAO implements HorarioDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT HORARIO_ID, DIA_SEMANA, HORA_INICIO, HORA_FIN FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( HORARIO_ID, DIA_SEMANA, HORA_INICIO, HORA_FIN ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET HORARIO_ID = ?, DIA_SEMANA = ?, HORA_INICIO = ?, HORA_FIN = ? WHERE HORARIO_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE HORARIO_ID = ?";

	/** 
	 * Index of column HORARIO_ID
	 */
	protected static final int COLUMN_HORARIO_ID = 1;

	/** 
	 * Index of column DIA_SEMANA
	 */
	protected static final int COLUMN_DIA_SEMANA = 2;

	/** 
	 * Index of column HORA_INICIO
	 */
	protected static final int COLUMN_HORA_INICIO = 3;

	/** 
	 * Index of column HORA_FIN
	 */
	protected static final int COLUMN_HORA_FIN = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column HORARIO_ID
	 */
	protected static final int PK_COLUMN_HORARIO_ID = 1;

	/** 
	 * Inserts a new row in the HORARIO table.
	 */
	public HorarioPk insert(Horario dto) throws HorarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getHorarioId() );
			stmt.setInt( index++, dto.getDiaSemana() );
			stmt.setTimestamp(index++, dto.getHoraInicio()==null ? null : new java.sql.Timestamp( dto.getHoraInicio().getTime() ) );
			stmt.setTimestamp(index++, dto.getHoraFin()==null ? null : new java.sql.Timestamp( dto.getHoraFin().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the HORARIO table.
	 */
	public void update(HorarioPk pk, Horario dto) throws HorarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getHorarioId() );
			stmt.setInt( index++, dto.getDiaSemana() );
			stmt.setTimestamp(index++, dto.getHoraInicio()==null ? null : new java.sql.Timestamp( dto.getHoraInicio().getTime() ) );
			stmt.setTimestamp(index++, dto.getHoraFin()==null ? null : new java.sql.Timestamp( dto.getHoraFin().getTime() ) );
			stmt.setLong( 5, pk.getHorarioId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the HORARIO table.
	 */
	public void delete(HorarioPk pk) throws HorarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getHorarioId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the HORARIO table that matches the specified primary-key value.
	 */
	public Horario findByPrimaryKey(HorarioPk pk) throws HorarioDaoException
	{
		return findByPrimaryKey( pk.getHorarioId() );
	}

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public Horario findByPrimaryKey(long horarioId) throws HorarioDaoException
	{
		Horario ret[] = findByDynamicSelect( SQL_SELECT + " WHERE HORARIO_ID = ?", new Object[] {  new Long(horarioId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the HORARIO table that match the criteria ''.
	 */
	public Horario[] findAll() throws HorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY HORARIO_ID", null );
	}

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORARIO_ID = :horarioId'.
	 */
	public Horario[] findWhereHorarioIdEquals(long horarioId) throws HorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HORARIO_ID = ? ORDER BY HORARIO_ID", new Object[] {  new Long(horarioId) } );
	}

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'DIA_SEMANA = :diaSemana'.
	 */
	public Horario[] findWhereDiaSemanaEquals(int diaSemana) throws HorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DIA_SEMANA = ? ORDER BY DIA_SEMANA", new Object[] {  new Integer(diaSemana) } );
	}

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORA_INICIO = :horaInicio'.
	 */
	public Horario[] findWhereHoraInicioEquals(Date horaInicio) throws HorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HORA_INICIO = ? ORDER BY HORA_INICIO", new Object[] { horaInicio==null ? null : new java.sql.Timestamp( horaInicio.getTime() ) } );
	}

	/** 
	 * Returns all rows from the HORARIO table that match the criteria 'HORA_FIN = :horaFin'.
	 */
	public Horario[] findWhereHoraFinEquals(Date horaFin) throws HorarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE HORA_FIN = ? ORDER BY HORA_FIN", new Object[] { horaFin==null ? null : new java.sql.Timestamp( horaFin.getTime() ) } );
	}

	/**
	 * Method 'HorarioDaoImpl'
	 * 
	 */
	public HorarioDaoImpl()
	{
	}

	/**
	 * Method 'HorarioDaoImpl'
	 * 
	 * @param userConn
	 */
	public HorarioDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.HORARIO";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Horario fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Horario dto = new Horario();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Horario[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Horario dto = new Horario();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Horario ret[] = new Horario[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Horario dto, ResultSet rs) throws SQLException
	{
		dto.setHorarioId( rs.getLong( COLUMN_HORARIO_ID ) );
		dto.setDiaSemana( rs.getInt( COLUMN_DIA_SEMANA ) );
		dto.setHoraInicio( rs.getTimestamp(COLUMN_HORA_INICIO ) );
		dto.setHoraFin( rs.getTimestamp(COLUMN_HORA_FIN ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Horario dto)
	{
	}

	/** 
	 * Returns all rows from the HORARIO table that match the specified arbitrary SQL statement
	 */
	public Horario[] findByDynamicSelect(String sql, Object[] sqlParams) throws HorarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the HORARIO table that match the specified arbitrary SQL statement
	 */
	public Horario[] findByDynamicWhere(String sql, Object[] sqlParams) throws HorarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HorarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
