/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PlanEstudiosDaoImpl extends AbstractDAO implements PlanEstudiosDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT PLAN_ESTUDIOS_ID, CLAVE, FECHA_APROBACION, FECHA_INICIO, FECHA_FIN FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( PLAN_ESTUDIOS_ID, CLAVE, FECHA_APROBACION, FECHA_INICIO, FECHA_FIN ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET PLAN_ESTUDIOS_ID = ?, CLAVE = ?, FECHA_APROBACION = ?, FECHA_INICIO = ?, FECHA_FIN = ? WHERE PLAN_ESTUDIOS_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE PLAN_ESTUDIOS_ID = ?";

	/** 
	 * Index of column PLAN_ESTUDIOS_ID
	 */
	protected static final int COLUMN_PLAN_ESTUDIOS_ID = 1;

	/** 
	 * Index of column CLAVE
	 */
	protected static final int COLUMN_CLAVE = 2;

	/** 
	 * Index of column FECHA_APROBACION
	 */
	protected static final int COLUMN_FECHA_APROBACION = 3;

	/** 
	 * Index of column FECHA_INICIO
	 */
	protected static final int COLUMN_FECHA_INICIO = 4;

	/** 
	 * Index of column FECHA_FIN
	 */
	protected static final int COLUMN_FECHA_FIN = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column PLAN_ESTUDIOS_ID
	 */
	protected static final int PK_COLUMN_PLAN_ESTUDIOS_ID = 1;

	/** 
	 * Inserts a new row in the PLAN_ESTUDIOS table.
	 */
	public PlanEstudiosPk insert(PlanEstudios dto) throws PlanEstudiosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getPlanEstudiosId() );
			stmt.setString( index++, dto.getClave() );
			stmt.setTimestamp(index++, dto.getFechaAprobacion()==null ? null : new java.sql.Timestamp( dto.getFechaAprobacion().getTime() ) );
			stmt.setTimestamp(index++, dto.getFechaInicio()==null ? null : new java.sql.Timestamp( dto.getFechaInicio().getTime() ) );
			stmt.setTimestamp(index++, dto.getFechaFin()==null ? null : new java.sql.Timestamp( dto.getFechaFin().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PlanEstudiosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the PLAN_ESTUDIOS table.
	 */
	public void update(PlanEstudiosPk pk, PlanEstudios dto) throws PlanEstudiosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getPlanEstudiosId() );
			stmt.setString( index++, dto.getClave() );
			stmt.setTimestamp(index++, dto.getFechaAprobacion()==null ? null : new java.sql.Timestamp( dto.getFechaAprobacion().getTime() ) );
			stmt.setTimestamp(index++, dto.getFechaInicio()==null ? null : new java.sql.Timestamp( dto.getFechaInicio().getTime() ) );
			stmt.setTimestamp(index++, dto.getFechaFin()==null ? null : new java.sql.Timestamp( dto.getFechaFin().getTime() ) );
			stmt.setInt( 6, pk.getPlanEstudiosId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PlanEstudiosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the PLAN_ESTUDIOS table.
	 */
	public void delete(PlanEstudiosPk pk) throws PlanEstudiosDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getPlanEstudiosId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PlanEstudiosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the PLAN_ESTUDIOS table that matches the specified primary-key value.
	 */
	public PlanEstudios findByPrimaryKey(PlanEstudiosPk pk) throws PlanEstudiosDaoException
	{
		return findByPrimaryKey( pk.getPlanEstudiosId() );
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public PlanEstudios findByPrimaryKey(int planEstudiosId) throws PlanEstudiosDaoException
	{
		PlanEstudios ret[] = findByDynamicSelect( SQL_SELECT + " WHERE PLAN_ESTUDIOS_ID = ?", new Object[] {  new Integer(planEstudiosId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria ''.
	 */
	public PlanEstudios[] findAll() throws PlanEstudiosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY PLAN_ESTUDIOS_ID", null );
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'PLAN_ESTUDIOS_ID = :planEstudiosId'.
	 */
	public PlanEstudios[] findWherePlanEstudiosIdEquals(int planEstudiosId) throws PlanEstudiosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PLAN_ESTUDIOS_ID = ? ORDER BY PLAN_ESTUDIOS_ID", new Object[] {  new Integer(planEstudiosId) } );
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'CLAVE = :clave'.
	 */
	public PlanEstudios[] findWhereClaveEquals(String clave) throws PlanEstudiosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CLAVE = ? ORDER BY CLAVE", new Object[] { clave } );
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'FECHA_APROBACION = :fechaAprobacion'.
	 */
	public PlanEstudios[] findWhereFechaAprobacionEquals(Date fechaAprobacion) throws PlanEstudiosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_APROBACION = ? ORDER BY FECHA_APROBACION", new Object[] { fechaAprobacion==null ? null : new java.sql.Timestamp( fechaAprobacion.getTime() ) } );
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'FECHA_INICIO = :fechaInicio'.
	 */
	public PlanEstudios[] findWhereFechaInicioEquals(Date fechaInicio) throws PlanEstudiosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_INICIO = ? ORDER BY FECHA_INICIO", new Object[] { fechaInicio==null ? null : new java.sql.Timestamp( fechaInicio.getTime() ) } );
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the criteria 'FECHA_FIN = :fechaFin'.
	 */
	public PlanEstudios[] findWhereFechaFinEquals(Date fechaFin) throws PlanEstudiosDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_FIN = ? ORDER BY FECHA_FIN", new Object[] { fechaFin==null ? null : new java.sql.Timestamp( fechaFin.getTime() ) } );
	}

	/**
	 * Method 'PlanEstudiosDaoImpl'
	 * 
	 */
	public PlanEstudiosDaoImpl()
	{
	}

	/**
	 * Method 'PlanEstudiosDaoImpl'
	 * 
	 * @param userConn
	 */
	public PlanEstudiosDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.PLAN_ESTUDIOS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PlanEstudios fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PlanEstudios dto = new PlanEstudios();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PlanEstudios[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PlanEstudios dto = new PlanEstudios();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PlanEstudios ret[] = new PlanEstudios[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PlanEstudios dto, ResultSet rs) throws SQLException
	{
		dto.setPlanEstudiosId( rs.getInt( COLUMN_PLAN_ESTUDIOS_ID ) );
		dto.setClave( rs.getString( COLUMN_CLAVE ) );
		dto.setFechaAprobacion( rs.getTimestamp(COLUMN_FECHA_APROBACION ) );
		dto.setFechaInicio( rs.getTimestamp(COLUMN_FECHA_INICIO ) );
		dto.setFechaFin( rs.getTimestamp(COLUMN_FECHA_FIN ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PlanEstudios dto)
	{
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the specified arbitrary SQL statement
	 */
	public PlanEstudios[] findByDynamicSelect(String sql, Object[] sqlParams) throws PlanEstudiosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PlanEstudiosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the PLAN_ESTUDIOS table that match the specified arbitrary SQL statement
	 */
	public PlanEstudios[] findByDynamicWhere(String sql, Object[] sqlParams) throws PlanEstudiosDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PlanEstudiosDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
