/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ProfesorDaoImpl extends AbstractDAO implements ProfesorDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT PROFESOR_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, RFC, FECHA_NACIMIENTO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( PROFESOR_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, RFC, FECHA_NACIMIENTO ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET PROFESOR_ID = ?, NOMBRE = ?, APELLIDO_PATERNO = ?, APELLIDO_MATERNO = ?, RFC = ?, FECHA_NACIMIENTO = ? WHERE PROFESOR_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE PROFESOR_ID = ?";

	/** 
	 * Index of column PROFESOR_ID
	 */
	protected static final int COLUMN_PROFESOR_ID = 1;

	/** 
	 * Index of column NOMBRE
	 */
	protected static final int COLUMN_NOMBRE = 2;

	/** 
	 * Index of column APELLIDO_PATERNO
	 */
	protected static final int COLUMN_APELLIDO_PATERNO = 3;

	/** 
	 * Index of column APELLIDO_MATERNO
	 */
	protected static final int COLUMN_APELLIDO_MATERNO = 4;

	/** 
	 * Index of column RFC
	 */
	protected static final int COLUMN_RFC = 5;

	/** 
	 * Index of column FECHA_NACIMIENTO
	 */
	protected static final int COLUMN_FECHA_NACIMIENTO = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column PROFESOR_ID
	 */
	protected static final int PK_COLUMN_PROFESOR_ID = 1;

	/** 
	 * Inserts a new row in the PROFESOR table.
	 */
	public ProfesorPk insert(Profesor dto) throws ProfesorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getProfesorId() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getApellidoPaterno() );
			stmt.setString( index++, dto.getApellidoMaterno() );
			stmt.setString( index++, dto.getRfc() );
			stmt.setTimestamp(index++, dto.getFechaNacimiento()==null ? null : new java.sql.Timestamp( dto.getFechaNacimiento().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProfesorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the PROFESOR table.
	 */
	public void update(ProfesorPk pk, Profesor dto) throws ProfesorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getProfesorId() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getApellidoPaterno() );
			stmt.setString( index++, dto.getApellidoMaterno() );
			stmt.setString( index++, dto.getRfc() );
			stmt.setTimestamp(index++, dto.getFechaNacimiento()==null ? null : new java.sql.Timestamp( dto.getFechaNacimiento().getTime() ) );
			stmt.setLong( 7, pk.getProfesorId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProfesorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the PROFESOR table.
	 */
	public void delete(ProfesorPk pk) throws ProfesorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getProfesorId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProfesorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the PROFESOR table that matches the specified primary-key value.
	 */
	public Profesor findByPrimaryKey(ProfesorPk pk) throws ProfesorDaoException
	{
		return findByPrimaryKey( pk.getProfesorId() );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Profesor findByPrimaryKey(long profesorId) throws ProfesorDaoException
	{
		Profesor ret[] = findByDynamicSelect( SQL_SELECT + " WHERE PROFESOR_ID = ?", new Object[] {  new Long(profesorId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria ''.
	 */
	public Profesor[] findAll() throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY PROFESOR_ID", null );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'PROFESOR_ID = :profesorId'.
	 */
	public Profesor[] findWhereProfesorIdEquals(long profesorId) throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PROFESOR_ID = ? ORDER BY PROFESOR_ID", new Object[] {  new Long(profesorId) } );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'NOMBRE = :nombre'.
	 */
	public Profesor[] findWhereNombreEquals(String nombre) throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE = ? ORDER BY NOMBRE", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'APELLIDO_PATERNO = :apellidoPaterno'.
	 */
	public Profesor[] findWhereApellidoPaternoEquals(String apellidoPaterno) throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE APELLIDO_PATERNO = ? ORDER BY APELLIDO_PATERNO", new Object[] { apellidoPaterno } );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'APELLIDO_MATERNO = :apellidoMaterno'.
	 */
	public Profesor[] findWhereApellidoMaternoEquals(String apellidoMaterno) throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE APELLIDO_MATERNO = ? ORDER BY APELLIDO_MATERNO", new Object[] { apellidoMaterno } );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'RFC = :rfc'.
	 */
	public Profesor[] findWhereRfcEquals(String rfc) throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE RFC = ? ORDER BY RFC", new Object[] { rfc } );
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the criteria 'FECHA_NACIMIENTO = :fechaNacimiento'.
	 */
	public Profesor[] findWhereFechaNacimientoEquals(Date fechaNacimiento) throws ProfesorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_NACIMIENTO = ? ORDER BY FECHA_NACIMIENTO", new Object[] { fechaNacimiento==null ? null : new java.sql.Timestamp( fechaNacimiento.getTime() ) } );
	}

	/**
	 * Method 'ProfesorDaoImpl'
	 * 
	 */
	public ProfesorDaoImpl()
	{
	}

	/**
	 * Method 'ProfesorDaoImpl'
	 * 
	 * @param userConn
	 */
	public ProfesorDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.PROFESOR";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Profesor fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Profesor dto = new Profesor();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Profesor[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Profesor dto = new Profesor();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Profesor ret[] = new Profesor[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Profesor dto, ResultSet rs) throws SQLException
	{
		dto.setProfesorId( rs.getLong( COLUMN_PROFESOR_ID ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setApellidoPaterno( rs.getString( COLUMN_APELLIDO_PATERNO ) );
		dto.setApellidoMaterno( rs.getString( COLUMN_APELLIDO_MATERNO ) );
		dto.setRfc( rs.getString( COLUMN_RFC ) );
		dto.setFechaNacimiento( rs.getTimestamp(COLUMN_FECHA_NACIMIENTO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Profesor dto)
	{
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the specified arbitrary SQL statement
	 */
	public Profesor[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProfesorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProfesorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the PROFESOR table that match the specified arbitrary SQL statement
	 */
	public Profesor[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProfesorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProfesorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
