/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.escuela.escuelaOracle.jdbc;

import com.escuela.escuelaOracle.dao.*;
import com.escuela.escuelaOracle.factory.*;
import java.util.Date;
import com.escuela.escuelaOracle.dto.*;
import com.escuela.escuelaOracle.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class SemestreDaoImpl extends AbstractDAO implements SemestreDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT SEMESTRE_ID, ANIO, PERIODO, FECHA_INICIO, FECHA_FIN FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( SEMESTRE_ID, ANIO, PERIODO, FECHA_INICIO, FECHA_FIN ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET SEMESTRE_ID = ?, ANIO = ?, PERIODO = ?, FECHA_INICIO = ?, FECHA_FIN = ? WHERE SEMESTRE_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE SEMESTRE_ID = ?";

	/** 
	 * Index of column SEMESTRE_ID
	 */
	protected static final int COLUMN_SEMESTRE_ID = 1;

	/** 
	 * Index of column ANIO
	 */
	protected static final int COLUMN_ANIO = 2;

	/** 
	 * Index of column PERIODO
	 */
	protected static final int COLUMN_PERIODO = 3;

	/** 
	 * Index of column FECHA_INICIO
	 */
	protected static final int COLUMN_FECHA_INICIO = 4;

	/** 
	 * Index of column FECHA_FIN
	 */
	protected static final int COLUMN_FECHA_FIN = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column SEMESTRE_ID
	 */
	protected static final int PK_COLUMN_SEMESTRE_ID = 1;

	/** 
	 * Inserts a new row in the SEMESTRE table.
	 */
	public SemestrePk insert(Semestre dto) throws SemestreDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getSemestreId() );
			stmt.setInt( index++, dto.getAnio() );
			stmt.setInt( index++, dto.getPeriodo() );
			stmt.setTimestamp(index++, dto.getFechaInicio()==null ? null : new java.sql.Timestamp( dto.getFechaInicio().getTime() ) );
			stmt.setTimestamp(index++, dto.getFechaFin()==null ? null : new java.sql.Timestamp( dto.getFechaFin().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SemestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the SEMESTRE table.
	 */
	public void update(SemestrePk pk, Semestre dto) throws SemestreDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getSemestreId() );
			stmt.setInt( index++, dto.getAnio() );
			stmt.setInt( index++, dto.getPeriodo() );
			stmt.setTimestamp(index++, dto.getFechaInicio()==null ? null : new java.sql.Timestamp( dto.getFechaInicio().getTime() ) );
			stmt.setTimestamp(index++, dto.getFechaFin()==null ? null : new java.sql.Timestamp( dto.getFechaFin().getTime() ) );
			stmt.setLong( 6, pk.getSemestreId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SemestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the SEMESTRE table.
	 */
	public void delete(SemestrePk pk) throws SemestreDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getSemestreId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SemestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the SEMESTRE table that matches the specified primary-key value.
	 */
	public Semestre findByPrimaryKey(SemestrePk pk) throws SemestreDaoException
	{
		return findByPrimaryKey( pk.getSemestreId() );
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Semestre findByPrimaryKey(long semestreId) throws SemestreDaoException
	{
		Semestre ret[] = findByDynamicSelect( SQL_SELECT + " WHERE SEMESTRE_ID = ?", new Object[] {  new Long(semestreId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria ''.
	 */
	public Semestre[] findAll() throws SemestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY SEMESTRE_ID", null );
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'SEMESTRE_ID = :semestreId'.
	 */
	public Semestre[] findWhereSemestreIdEquals(long semestreId) throws SemestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SEMESTRE_ID = ? ORDER BY SEMESTRE_ID", new Object[] {  new Long(semestreId) } );
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'ANIO = :anio'.
	 */
	public Semestre[] findWhereAnioEquals(int anio) throws SemestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ANIO = ? ORDER BY ANIO", new Object[] {  new Integer(anio) } );
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'PERIODO = :periodo'.
	 */
	public Semestre[] findWherePeriodoEquals(int periodo) throws SemestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE PERIODO = ? ORDER BY PERIODO", new Object[] {  new Integer(periodo) } );
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'FECHA_INICIO = :fechaInicio'.
	 */
	public Semestre[] findWhereFechaInicioEquals(Date fechaInicio) throws SemestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_INICIO = ? ORDER BY FECHA_INICIO", new Object[] { fechaInicio==null ? null : new java.sql.Timestamp( fechaInicio.getTime() ) } );
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the criteria 'FECHA_FIN = :fechaFin'.
	 */
	public Semestre[] findWhereFechaFinEquals(Date fechaFin) throws SemestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_FIN = ? ORDER BY FECHA_FIN", new Object[] { fechaFin==null ? null : new java.sql.Timestamp( fechaFin.getTime() ) } );
	}

	/**
	 * Method 'SemestreDaoImpl'
	 * 
	 */
	public SemestreDaoImpl()
	{
	}

	/**
	 * Method 'SemestreDaoImpl'
	 * 
	 * @param userConn
	 */
	public SemestreDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "ESCUELA.SEMESTRE";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Semestre fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Semestre dto = new Semestre();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Semestre[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Semestre dto = new Semestre();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Semestre ret[] = new Semestre[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Semestre dto, ResultSet rs) throws SQLException
	{
		dto.setSemestreId( rs.getLong( COLUMN_SEMESTRE_ID ) );
		dto.setAnio( rs.getInt( COLUMN_ANIO ) );
		dto.setPeriodo( rs.getInt( COLUMN_PERIODO ) );
		dto.setFechaInicio( rs.getTimestamp(COLUMN_FECHA_INICIO ) );
		dto.setFechaFin( rs.getTimestamp(COLUMN_FECHA_FIN ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Semestre dto)
	{
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the specified arbitrary SQL statement
	 */
	public Semestre[] findByDynamicSelect(String sql, Object[] sqlParams) throws SemestreDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SemestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the SEMESTRE table that match the specified arbitrary SQL statement
	 */
	public Semestre[] findByDynamicWhere(String sql, Object[] sqlParams) throws SemestreDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SemestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
